// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module MatrixMult_NoCache_dataflow_in_loop_VITIS_LOOP_24_1_1 (
        size,
        m_axi_matrix_a_0_AWVALID,
        m_axi_matrix_a_0_AWREADY,
        m_axi_matrix_a_0_AWADDR,
        m_axi_matrix_a_0_AWID,
        m_axi_matrix_a_0_AWLEN,
        m_axi_matrix_a_0_AWSIZE,
        m_axi_matrix_a_0_AWBURST,
        m_axi_matrix_a_0_AWLOCK,
        m_axi_matrix_a_0_AWCACHE,
        m_axi_matrix_a_0_AWPROT,
        m_axi_matrix_a_0_AWQOS,
        m_axi_matrix_a_0_AWREGION,
        m_axi_matrix_a_0_AWUSER,
        m_axi_matrix_a_0_WVALID,
        m_axi_matrix_a_0_WREADY,
        m_axi_matrix_a_0_WDATA,
        m_axi_matrix_a_0_WSTRB,
        m_axi_matrix_a_0_WLAST,
        m_axi_matrix_a_0_WID,
        m_axi_matrix_a_0_WUSER,
        m_axi_matrix_a_0_ARVALID,
        m_axi_matrix_a_0_ARREADY,
        m_axi_matrix_a_0_ARADDR,
        m_axi_matrix_a_0_ARID,
        m_axi_matrix_a_0_ARLEN,
        m_axi_matrix_a_0_ARSIZE,
        m_axi_matrix_a_0_ARBURST,
        m_axi_matrix_a_0_ARLOCK,
        m_axi_matrix_a_0_ARCACHE,
        m_axi_matrix_a_0_ARPROT,
        m_axi_matrix_a_0_ARQOS,
        m_axi_matrix_a_0_ARREGION,
        m_axi_matrix_a_0_ARUSER,
        m_axi_matrix_a_0_RVALID,
        m_axi_matrix_a_0_RREADY,
        m_axi_matrix_a_0_RDATA,
        m_axi_matrix_a_0_RLAST,
        m_axi_matrix_a_0_RID,
        m_axi_matrix_a_0_RFIFONUM,
        m_axi_matrix_a_0_RUSER,
        m_axi_matrix_a_0_RRESP,
        m_axi_matrix_a_0_BVALID,
        m_axi_matrix_a_0_BREADY,
        m_axi_matrix_a_0_BRESP,
        m_axi_matrix_a_0_BID,
        m_axi_matrix_a_0_BUSER,
        matrix_in_1,
        m_axi_matrix_b_0_AWVALID,
        m_axi_matrix_b_0_AWREADY,
        m_axi_matrix_b_0_AWADDR,
        m_axi_matrix_b_0_AWID,
        m_axi_matrix_b_0_AWLEN,
        m_axi_matrix_b_0_AWSIZE,
        m_axi_matrix_b_0_AWBURST,
        m_axi_matrix_b_0_AWLOCK,
        m_axi_matrix_b_0_AWCACHE,
        m_axi_matrix_b_0_AWPROT,
        m_axi_matrix_b_0_AWQOS,
        m_axi_matrix_b_0_AWREGION,
        m_axi_matrix_b_0_AWUSER,
        m_axi_matrix_b_0_WVALID,
        m_axi_matrix_b_0_WREADY,
        m_axi_matrix_b_0_WDATA,
        m_axi_matrix_b_0_WSTRB,
        m_axi_matrix_b_0_WLAST,
        m_axi_matrix_b_0_WID,
        m_axi_matrix_b_0_WUSER,
        m_axi_matrix_b_0_ARVALID,
        m_axi_matrix_b_0_ARREADY,
        m_axi_matrix_b_0_ARADDR,
        m_axi_matrix_b_0_ARID,
        m_axi_matrix_b_0_ARLEN,
        m_axi_matrix_b_0_ARSIZE,
        m_axi_matrix_b_0_ARBURST,
        m_axi_matrix_b_0_ARLOCK,
        m_axi_matrix_b_0_ARCACHE,
        m_axi_matrix_b_0_ARPROT,
        m_axi_matrix_b_0_ARQOS,
        m_axi_matrix_b_0_ARREGION,
        m_axi_matrix_b_0_ARUSER,
        m_axi_matrix_b_0_RVALID,
        m_axi_matrix_b_0_RREADY,
        m_axi_matrix_b_0_RDATA,
        m_axi_matrix_b_0_RLAST,
        m_axi_matrix_b_0_RID,
        m_axi_matrix_b_0_RFIFONUM,
        m_axi_matrix_b_0_RUSER,
        m_axi_matrix_b_0_RRESP,
        m_axi_matrix_b_0_BVALID,
        m_axi_matrix_b_0_BREADY,
        m_axi_matrix_b_0_BRESP,
        m_axi_matrix_b_0_BID,
        m_axi_matrix_b_0_BUSER,
        matrix_in_2,
        m_axi_matrix_c_0_AWVALID,
        m_axi_matrix_c_0_AWREADY,
        m_axi_matrix_c_0_AWADDR,
        m_axi_matrix_c_0_AWID,
        m_axi_matrix_c_0_AWLEN,
        m_axi_matrix_c_0_AWSIZE,
        m_axi_matrix_c_0_AWBURST,
        m_axi_matrix_c_0_AWLOCK,
        m_axi_matrix_c_0_AWCACHE,
        m_axi_matrix_c_0_AWPROT,
        m_axi_matrix_c_0_AWQOS,
        m_axi_matrix_c_0_AWREGION,
        m_axi_matrix_c_0_AWUSER,
        m_axi_matrix_c_0_WVALID,
        m_axi_matrix_c_0_WREADY,
        m_axi_matrix_c_0_WDATA,
        m_axi_matrix_c_0_WSTRB,
        m_axi_matrix_c_0_WLAST,
        m_axi_matrix_c_0_WID,
        m_axi_matrix_c_0_WUSER,
        m_axi_matrix_c_0_ARVALID,
        m_axi_matrix_c_0_ARREADY,
        m_axi_matrix_c_0_ARADDR,
        m_axi_matrix_c_0_ARID,
        m_axi_matrix_c_0_ARLEN,
        m_axi_matrix_c_0_ARSIZE,
        m_axi_matrix_c_0_ARBURST,
        m_axi_matrix_c_0_ARLOCK,
        m_axi_matrix_c_0_ARCACHE,
        m_axi_matrix_c_0_ARPROT,
        m_axi_matrix_c_0_ARQOS,
        m_axi_matrix_c_0_ARREGION,
        m_axi_matrix_c_0_ARUSER,
        m_axi_matrix_c_0_RVALID,
        m_axi_matrix_c_0_RREADY,
        m_axi_matrix_c_0_RDATA,
        m_axi_matrix_c_0_RLAST,
        m_axi_matrix_c_0_RID,
        m_axi_matrix_c_0_RFIFONUM,
        m_axi_matrix_c_0_RUSER,
        m_axi_matrix_c_0_RRESP,
        m_axi_matrix_c_0_BVALID,
        m_axi_matrix_c_0_BREADY,
        m_axi_matrix_c_0_BRESP,
        m_axi_matrix_c_0_BID,
        m_axi_matrix_c_0_BUSER,
        matrix_out,
        ap_clk,
        ap_rst,
        size_ap_vld,
        matrix_in_1_ap_vld,
        matrix_in_2_ap_vld,
        ap_start,
        matrix_out_ap_vld,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [15:0] size;
output   m_axi_matrix_a_0_AWVALID;
input   m_axi_matrix_a_0_AWREADY;
output  [63:0] m_axi_matrix_a_0_AWADDR;
output  [0:0] m_axi_matrix_a_0_AWID;
output  [31:0] m_axi_matrix_a_0_AWLEN;
output  [2:0] m_axi_matrix_a_0_AWSIZE;
output  [1:0] m_axi_matrix_a_0_AWBURST;
output  [1:0] m_axi_matrix_a_0_AWLOCK;
output  [3:0] m_axi_matrix_a_0_AWCACHE;
output  [2:0] m_axi_matrix_a_0_AWPROT;
output  [3:0] m_axi_matrix_a_0_AWQOS;
output  [3:0] m_axi_matrix_a_0_AWREGION;
output  [0:0] m_axi_matrix_a_0_AWUSER;
output   m_axi_matrix_a_0_WVALID;
input   m_axi_matrix_a_0_WREADY;
output  [15:0] m_axi_matrix_a_0_WDATA;
output  [1:0] m_axi_matrix_a_0_WSTRB;
output   m_axi_matrix_a_0_WLAST;
output  [0:0] m_axi_matrix_a_0_WID;
output  [0:0] m_axi_matrix_a_0_WUSER;
output   m_axi_matrix_a_0_ARVALID;
input   m_axi_matrix_a_0_ARREADY;
output  [63:0] m_axi_matrix_a_0_ARADDR;
output  [0:0] m_axi_matrix_a_0_ARID;
output  [31:0] m_axi_matrix_a_0_ARLEN;
output  [2:0] m_axi_matrix_a_0_ARSIZE;
output  [1:0] m_axi_matrix_a_0_ARBURST;
output  [1:0] m_axi_matrix_a_0_ARLOCK;
output  [3:0] m_axi_matrix_a_0_ARCACHE;
output  [2:0] m_axi_matrix_a_0_ARPROT;
output  [3:0] m_axi_matrix_a_0_ARQOS;
output  [3:0] m_axi_matrix_a_0_ARREGION;
output  [0:0] m_axi_matrix_a_0_ARUSER;
input   m_axi_matrix_a_0_RVALID;
output   m_axi_matrix_a_0_RREADY;
input  [15:0] m_axi_matrix_a_0_RDATA;
input   m_axi_matrix_a_0_RLAST;
input  [0:0] m_axi_matrix_a_0_RID;
input  [12:0] m_axi_matrix_a_0_RFIFONUM;
input  [0:0] m_axi_matrix_a_0_RUSER;
input  [1:0] m_axi_matrix_a_0_RRESP;
input   m_axi_matrix_a_0_BVALID;
output   m_axi_matrix_a_0_BREADY;
input  [1:0] m_axi_matrix_a_0_BRESP;
input  [0:0] m_axi_matrix_a_0_BID;
input  [0:0] m_axi_matrix_a_0_BUSER;
input  [63:0] matrix_in_1;
output   m_axi_matrix_b_0_AWVALID;
input   m_axi_matrix_b_0_AWREADY;
output  [63:0] m_axi_matrix_b_0_AWADDR;
output  [0:0] m_axi_matrix_b_0_AWID;
output  [31:0] m_axi_matrix_b_0_AWLEN;
output  [2:0] m_axi_matrix_b_0_AWSIZE;
output  [1:0] m_axi_matrix_b_0_AWBURST;
output  [1:0] m_axi_matrix_b_0_AWLOCK;
output  [3:0] m_axi_matrix_b_0_AWCACHE;
output  [2:0] m_axi_matrix_b_0_AWPROT;
output  [3:0] m_axi_matrix_b_0_AWQOS;
output  [3:0] m_axi_matrix_b_0_AWREGION;
output  [0:0] m_axi_matrix_b_0_AWUSER;
output   m_axi_matrix_b_0_WVALID;
input   m_axi_matrix_b_0_WREADY;
output  [15:0] m_axi_matrix_b_0_WDATA;
output  [1:0] m_axi_matrix_b_0_WSTRB;
output   m_axi_matrix_b_0_WLAST;
output  [0:0] m_axi_matrix_b_0_WID;
output  [0:0] m_axi_matrix_b_0_WUSER;
output   m_axi_matrix_b_0_ARVALID;
input   m_axi_matrix_b_0_ARREADY;
output  [63:0] m_axi_matrix_b_0_ARADDR;
output  [0:0] m_axi_matrix_b_0_ARID;
output  [31:0] m_axi_matrix_b_0_ARLEN;
output  [2:0] m_axi_matrix_b_0_ARSIZE;
output  [1:0] m_axi_matrix_b_0_ARBURST;
output  [1:0] m_axi_matrix_b_0_ARLOCK;
output  [3:0] m_axi_matrix_b_0_ARCACHE;
output  [2:0] m_axi_matrix_b_0_ARPROT;
output  [3:0] m_axi_matrix_b_0_ARQOS;
output  [3:0] m_axi_matrix_b_0_ARREGION;
output  [0:0] m_axi_matrix_b_0_ARUSER;
input   m_axi_matrix_b_0_RVALID;
output   m_axi_matrix_b_0_RREADY;
input  [15:0] m_axi_matrix_b_0_RDATA;
input   m_axi_matrix_b_0_RLAST;
input  [0:0] m_axi_matrix_b_0_RID;
input  [12:0] m_axi_matrix_b_0_RFIFONUM;
input  [0:0] m_axi_matrix_b_0_RUSER;
input  [1:0] m_axi_matrix_b_0_RRESP;
input   m_axi_matrix_b_0_BVALID;
output   m_axi_matrix_b_0_BREADY;
input  [1:0] m_axi_matrix_b_0_BRESP;
input  [0:0] m_axi_matrix_b_0_BID;
input  [0:0] m_axi_matrix_b_0_BUSER;
input  [63:0] matrix_in_2;
output   m_axi_matrix_c_0_AWVALID;
input   m_axi_matrix_c_0_AWREADY;
output  [63:0] m_axi_matrix_c_0_AWADDR;
output  [0:0] m_axi_matrix_c_0_AWID;
output  [31:0] m_axi_matrix_c_0_AWLEN;
output  [2:0] m_axi_matrix_c_0_AWSIZE;
output  [1:0] m_axi_matrix_c_0_AWBURST;
output  [1:0] m_axi_matrix_c_0_AWLOCK;
output  [3:0] m_axi_matrix_c_0_AWCACHE;
output  [2:0] m_axi_matrix_c_0_AWPROT;
output  [3:0] m_axi_matrix_c_0_AWQOS;
output  [3:0] m_axi_matrix_c_0_AWREGION;
output  [0:0] m_axi_matrix_c_0_AWUSER;
output   m_axi_matrix_c_0_WVALID;
input   m_axi_matrix_c_0_WREADY;
output  [31:0] m_axi_matrix_c_0_WDATA;
output  [3:0] m_axi_matrix_c_0_WSTRB;
output   m_axi_matrix_c_0_WLAST;
output  [0:0] m_axi_matrix_c_0_WID;
output  [0:0] m_axi_matrix_c_0_WUSER;
output   m_axi_matrix_c_0_ARVALID;
input   m_axi_matrix_c_0_ARREADY;
output  [63:0] m_axi_matrix_c_0_ARADDR;
output  [0:0] m_axi_matrix_c_0_ARID;
output  [31:0] m_axi_matrix_c_0_ARLEN;
output  [2:0] m_axi_matrix_c_0_ARSIZE;
output  [1:0] m_axi_matrix_c_0_ARBURST;
output  [1:0] m_axi_matrix_c_0_ARLOCK;
output  [3:0] m_axi_matrix_c_0_ARCACHE;
output  [2:0] m_axi_matrix_c_0_ARPROT;
output  [3:0] m_axi_matrix_c_0_ARQOS;
output  [3:0] m_axi_matrix_c_0_ARREGION;
output  [0:0] m_axi_matrix_c_0_ARUSER;
input   m_axi_matrix_c_0_RVALID;
output   m_axi_matrix_c_0_RREADY;
input  [31:0] m_axi_matrix_c_0_RDATA;
input   m_axi_matrix_c_0_RLAST;
input  [0:0] m_axi_matrix_c_0_RID;
input  [11:0] m_axi_matrix_c_0_RFIFONUM;
input  [0:0] m_axi_matrix_c_0_RUSER;
input  [1:0] m_axi_matrix_c_0_RRESP;
input   m_axi_matrix_c_0_BVALID;
output   m_axi_matrix_c_0_BREADY;
input  [1:0] m_axi_matrix_c_0_BRESP;
input  [0:0] m_axi_matrix_c_0_BID;
input  [0:0] m_axi_matrix_c_0_BUSER;
input  [63:0] matrix_out;
input   ap_clk;
input   ap_rst;
input   size_ap_vld;
input   matrix_in_1_ap_vld;
input   matrix_in_2_ap_vld;
input   ap_start;
input   matrix_out_ap_vld;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_start;
wire    dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_done;
wire    dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_continue;
wire    dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_idle;
wire    dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_ready;
wire    dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWVALID;
wire   [63:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWADDR;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWID;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWLEN;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWSIZE;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWBURST;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWLOCK;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWCACHE;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWPROT;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWQOS;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWREGION;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWUSER;
wire    dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_WVALID;
wire   [15:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_WDATA;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_WSTRB;
wire    dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_WLAST;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_WID;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_WUSER;
wire    dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARVALID;
wire   [63:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARADDR;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARID;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARLEN;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARSIZE;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARBURST;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARLOCK;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARCACHE;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARPROT;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARQOS;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARREGION;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARUSER;
wire    dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_RREADY;
wire    dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_BREADY;
wire    dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWVALID;
wire   [63:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWADDR;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWID;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWLEN;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWSIZE;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWBURST;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWLOCK;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWCACHE;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWPROT;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWQOS;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWREGION;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWUSER;
wire    dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_WVALID;
wire   [15:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_WDATA;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_WSTRB;
wire    dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_WLAST;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_WID;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_WUSER;
wire    dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARVALID;
wire   [63:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARADDR;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARID;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARLEN;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARSIZE;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARBURST;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARLOCK;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARCACHE;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARPROT;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARQOS;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARREGION;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARUSER;
wire    dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_RREADY;
wire    dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_BREADY;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_0;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_1;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_2;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_3;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_4;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_5;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_6;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_7;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_8;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_9;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_10;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_11;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_12;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_13;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_14;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_15;
wire    ap_channel_done_Matrix_4x4_final15;
wire    Matrix_4x4_final15_full_n;
reg    ap_sync_reg_channel_write_Matrix_4x4_final15;
wire    ap_sync_channel_write_Matrix_4x4_final15;
wire    matrixStitcher11_U0_ap_start;
wire    matrixStitcher11_U0_ap_done;
wire    matrixStitcher11_U0_ap_continue;
wire    matrixStitcher11_U0_ap_idle;
wire    matrixStitcher11_U0_ap_ready;
wire    matrixStitcher11_U0_m_axi_matrix_c_0_AWVALID;
wire   [63:0] matrixStitcher11_U0_m_axi_matrix_c_0_AWADDR;
wire   [0:0] matrixStitcher11_U0_m_axi_matrix_c_0_AWID;
wire   [31:0] matrixStitcher11_U0_m_axi_matrix_c_0_AWLEN;
wire   [2:0] matrixStitcher11_U0_m_axi_matrix_c_0_AWSIZE;
wire   [1:0] matrixStitcher11_U0_m_axi_matrix_c_0_AWBURST;
wire   [1:0] matrixStitcher11_U0_m_axi_matrix_c_0_AWLOCK;
wire   [3:0] matrixStitcher11_U0_m_axi_matrix_c_0_AWCACHE;
wire   [2:0] matrixStitcher11_U0_m_axi_matrix_c_0_AWPROT;
wire   [3:0] matrixStitcher11_U0_m_axi_matrix_c_0_AWQOS;
wire   [3:0] matrixStitcher11_U0_m_axi_matrix_c_0_AWREGION;
wire   [0:0] matrixStitcher11_U0_m_axi_matrix_c_0_AWUSER;
wire    matrixStitcher11_U0_m_axi_matrix_c_0_WVALID;
wire   [31:0] matrixStitcher11_U0_m_axi_matrix_c_0_WDATA;
wire   [3:0] matrixStitcher11_U0_m_axi_matrix_c_0_WSTRB;
wire    matrixStitcher11_U0_m_axi_matrix_c_0_WLAST;
wire   [0:0] matrixStitcher11_U0_m_axi_matrix_c_0_WID;
wire   [0:0] matrixStitcher11_U0_m_axi_matrix_c_0_WUSER;
wire    matrixStitcher11_U0_m_axi_matrix_c_0_ARVALID;
wire   [63:0] matrixStitcher11_U0_m_axi_matrix_c_0_ARADDR;
wire   [0:0] matrixStitcher11_U0_m_axi_matrix_c_0_ARID;
wire   [31:0] matrixStitcher11_U0_m_axi_matrix_c_0_ARLEN;
wire   [2:0] matrixStitcher11_U0_m_axi_matrix_c_0_ARSIZE;
wire   [1:0] matrixStitcher11_U0_m_axi_matrix_c_0_ARBURST;
wire   [1:0] matrixStitcher11_U0_m_axi_matrix_c_0_ARLOCK;
wire   [3:0] matrixStitcher11_U0_m_axi_matrix_c_0_ARCACHE;
wire   [2:0] matrixStitcher11_U0_m_axi_matrix_c_0_ARPROT;
wire   [3:0] matrixStitcher11_U0_m_axi_matrix_c_0_ARQOS;
wire   [3:0] matrixStitcher11_U0_m_axi_matrix_c_0_ARREGION;
wire   [0:0] matrixStitcher11_U0_m_axi_matrix_c_0_ARUSER;
wire    matrixStitcher11_U0_m_axi_matrix_c_0_RREADY;
wire    matrixStitcher11_U0_m_axi_matrix_c_0_BREADY;
wire    Matrix_4x4_final_full_n;
wire   [31:0] Matrix_4x4_final_dout;
wire    Matrix_4x4_final_empty_n;
wire   [2:0] Matrix_4x4_final_num_data_valid;
wire   [2:0] Matrix_4x4_final_fifo_cap;
wire    Matrix_4x4_final_1_full_n;
wire   [31:0] Matrix_4x4_final_1_dout;
wire    Matrix_4x4_final_1_empty_n;
wire   [2:0] Matrix_4x4_final_1_num_data_valid;
wire   [2:0] Matrix_4x4_final_1_fifo_cap;
wire    Matrix_4x4_final_2_full_n;
wire   [31:0] Matrix_4x4_final_2_dout;
wire    Matrix_4x4_final_2_empty_n;
wire   [2:0] Matrix_4x4_final_2_num_data_valid;
wire   [2:0] Matrix_4x4_final_2_fifo_cap;
wire    Matrix_4x4_final_3_full_n;
wire   [31:0] Matrix_4x4_final_3_dout;
wire    Matrix_4x4_final_3_empty_n;
wire   [2:0] Matrix_4x4_final_3_num_data_valid;
wire   [2:0] Matrix_4x4_final_3_fifo_cap;
wire    Matrix_4x4_final_4_full_n;
wire   [31:0] Matrix_4x4_final_4_dout;
wire    Matrix_4x4_final_4_empty_n;
wire   [2:0] Matrix_4x4_final_4_num_data_valid;
wire   [2:0] Matrix_4x4_final_4_fifo_cap;
wire    Matrix_4x4_final_5_full_n;
wire   [31:0] Matrix_4x4_final_5_dout;
wire    Matrix_4x4_final_5_empty_n;
wire   [2:0] Matrix_4x4_final_5_num_data_valid;
wire   [2:0] Matrix_4x4_final_5_fifo_cap;
wire    Matrix_4x4_final_6_full_n;
wire   [31:0] Matrix_4x4_final_6_dout;
wire    Matrix_4x4_final_6_empty_n;
wire   [2:0] Matrix_4x4_final_6_num_data_valid;
wire   [2:0] Matrix_4x4_final_6_fifo_cap;
wire    Matrix_4x4_final_7_full_n;
wire   [31:0] Matrix_4x4_final_7_dout;
wire    Matrix_4x4_final_7_empty_n;
wire   [2:0] Matrix_4x4_final_7_num_data_valid;
wire   [2:0] Matrix_4x4_final_7_fifo_cap;
wire    Matrix_4x4_final_8_full_n;
wire   [31:0] Matrix_4x4_final_8_dout;
wire    Matrix_4x4_final_8_empty_n;
wire   [2:0] Matrix_4x4_final_8_num_data_valid;
wire   [2:0] Matrix_4x4_final_8_fifo_cap;
wire    Matrix_4x4_final_9_full_n;
wire   [31:0] Matrix_4x4_final_9_dout;
wire    Matrix_4x4_final_9_empty_n;
wire   [2:0] Matrix_4x4_final_9_num_data_valid;
wire   [2:0] Matrix_4x4_final_9_fifo_cap;
wire    Matrix_4x4_final_10_full_n;
wire   [31:0] Matrix_4x4_final_10_dout;
wire    Matrix_4x4_final_10_empty_n;
wire   [2:0] Matrix_4x4_final_10_num_data_valid;
wire   [2:0] Matrix_4x4_final_10_fifo_cap;
wire    Matrix_4x4_final_11_full_n;
wire   [31:0] Matrix_4x4_final_11_dout;
wire    Matrix_4x4_final_11_empty_n;
wire   [2:0] Matrix_4x4_final_11_num_data_valid;
wire   [2:0] Matrix_4x4_final_11_fifo_cap;
wire    Matrix_4x4_final_12_full_n;
wire   [31:0] Matrix_4x4_final_12_dout;
wire    Matrix_4x4_final_12_empty_n;
wire   [2:0] Matrix_4x4_final_12_num_data_valid;
wire   [2:0] Matrix_4x4_final_12_fifo_cap;
wire    Matrix_4x4_final_13_full_n;
wire   [31:0] Matrix_4x4_final_13_dout;
wire    Matrix_4x4_final_13_empty_n;
wire   [2:0] Matrix_4x4_final_13_num_data_valid;
wire   [2:0] Matrix_4x4_final_13_fifo_cap;
wire    Matrix_4x4_final_14_full_n;
wire   [31:0] Matrix_4x4_final_14_dout;
wire    Matrix_4x4_final_14_empty_n;
wire   [2:0] Matrix_4x4_final_14_num_data_valid;
wire   [2:0] Matrix_4x4_final_14_fifo_cap;
wire   [31:0] Matrix_4x4_final15_dout;
wire    Matrix_4x4_final15_empty_n;
wire   [2:0] Matrix_4x4_final15_num_data_valid;
wire   [2:0] Matrix_4x4_final15_fifo_cap;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_Matrix_4x4_final15 = 1'b0;
end

MatrixMult_NoCache_dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10 dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_start),
    .ap_done(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_done),
    .ap_continue(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_continue),
    .ap_idle(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_idle),
    .ap_ready(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_ready),
    .size(size),
    .m_axi_matrix_a_0_AWVALID(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWVALID),
    .m_axi_matrix_a_0_AWREADY(1'b0),
    .m_axi_matrix_a_0_AWADDR(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWADDR),
    .m_axi_matrix_a_0_AWID(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWID),
    .m_axi_matrix_a_0_AWLEN(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWLEN),
    .m_axi_matrix_a_0_AWSIZE(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWSIZE),
    .m_axi_matrix_a_0_AWBURST(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWBURST),
    .m_axi_matrix_a_0_AWLOCK(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWLOCK),
    .m_axi_matrix_a_0_AWCACHE(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWCACHE),
    .m_axi_matrix_a_0_AWPROT(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWPROT),
    .m_axi_matrix_a_0_AWQOS(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWQOS),
    .m_axi_matrix_a_0_AWREGION(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWREGION),
    .m_axi_matrix_a_0_AWUSER(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWUSER),
    .m_axi_matrix_a_0_WVALID(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_WVALID),
    .m_axi_matrix_a_0_WREADY(1'b0),
    .m_axi_matrix_a_0_WDATA(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_WDATA),
    .m_axi_matrix_a_0_WSTRB(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_WSTRB),
    .m_axi_matrix_a_0_WLAST(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_WLAST),
    .m_axi_matrix_a_0_WID(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_WID),
    .m_axi_matrix_a_0_WUSER(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_WUSER),
    .m_axi_matrix_a_0_ARVALID(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARVALID),
    .m_axi_matrix_a_0_ARREADY(m_axi_matrix_a_0_ARREADY),
    .m_axi_matrix_a_0_ARADDR(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARADDR),
    .m_axi_matrix_a_0_ARID(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARID),
    .m_axi_matrix_a_0_ARLEN(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARLEN),
    .m_axi_matrix_a_0_ARSIZE(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARSIZE),
    .m_axi_matrix_a_0_ARBURST(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARBURST),
    .m_axi_matrix_a_0_ARLOCK(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARLOCK),
    .m_axi_matrix_a_0_ARCACHE(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARCACHE),
    .m_axi_matrix_a_0_ARPROT(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARPROT),
    .m_axi_matrix_a_0_ARQOS(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARQOS),
    .m_axi_matrix_a_0_ARREGION(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARREGION),
    .m_axi_matrix_a_0_ARUSER(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARUSER),
    .m_axi_matrix_a_0_RVALID(m_axi_matrix_a_0_RVALID),
    .m_axi_matrix_a_0_RREADY(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_RREADY),
    .m_axi_matrix_a_0_RDATA(m_axi_matrix_a_0_RDATA),
    .m_axi_matrix_a_0_RLAST(m_axi_matrix_a_0_RLAST),
    .m_axi_matrix_a_0_RID(m_axi_matrix_a_0_RID),
    .m_axi_matrix_a_0_RFIFONUM(m_axi_matrix_a_0_RFIFONUM),
    .m_axi_matrix_a_0_RUSER(m_axi_matrix_a_0_RUSER),
    .m_axi_matrix_a_0_RRESP(m_axi_matrix_a_0_RRESP),
    .m_axi_matrix_a_0_BVALID(1'b0),
    .m_axi_matrix_a_0_BREADY(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_BREADY),
    .m_axi_matrix_a_0_BRESP(2'd0),
    .m_axi_matrix_a_0_BID(1'd0),
    .m_axi_matrix_a_0_BUSER(1'd0),
    .matrix_in_1(matrix_in_1),
    .m_axi_matrix_b_0_AWVALID(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWVALID),
    .m_axi_matrix_b_0_AWREADY(1'b0),
    .m_axi_matrix_b_0_AWADDR(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWADDR),
    .m_axi_matrix_b_0_AWID(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWID),
    .m_axi_matrix_b_0_AWLEN(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWLEN),
    .m_axi_matrix_b_0_AWSIZE(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWSIZE),
    .m_axi_matrix_b_0_AWBURST(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWBURST),
    .m_axi_matrix_b_0_AWLOCK(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWLOCK),
    .m_axi_matrix_b_0_AWCACHE(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWCACHE),
    .m_axi_matrix_b_0_AWPROT(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWPROT),
    .m_axi_matrix_b_0_AWQOS(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWQOS),
    .m_axi_matrix_b_0_AWREGION(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWREGION),
    .m_axi_matrix_b_0_AWUSER(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWUSER),
    .m_axi_matrix_b_0_WVALID(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_WVALID),
    .m_axi_matrix_b_0_WREADY(1'b0),
    .m_axi_matrix_b_0_WDATA(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_WDATA),
    .m_axi_matrix_b_0_WSTRB(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_WSTRB),
    .m_axi_matrix_b_0_WLAST(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_WLAST),
    .m_axi_matrix_b_0_WID(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_WID),
    .m_axi_matrix_b_0_WUSER(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_WUSER),
    .m_axi_matrix_b_0_ARVALID(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARVALID),
    .m_axi_matrix_b_0_ARREADY(m_axi_matrix_b_0_ARREADY),
    .m_axi_matrix_b_0_ARADDR(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARADDR),
    .m_axi_matrix_b_0_ARID(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARID),
    .m_axi_matrix_b_0_ARLEN(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARLEN),
    .m_axi_matrix_b_0_ARSIZE(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARSIZE),
    .m_axi_matrix_b_0_ARBURST(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARBURST),
    .m_axi_matrix_b_0_ARLOCK(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARLOCK),
    .m_axi_matrix_b_0_ARCACHE(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARCACHE),
    .m_axi_matrix_b_0_ARPROT(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARPROT),
    .m_axi_matrix_b_0_ARQOS(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARQOS),
    .m_axi_matrix_b_0_ARREGION(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARREGION),
    .m_axi_matrix_b_0_ARUSER(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARUSER),
    .m_axi_matrix_b_0_RVALID(m_axi_matrix_b_0_RVALID),
    .m_axi_matrix_b_0_RREADY(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_RREADY),
    .m_axi_matrix_b_0_RDATA(m_axi_matrix_b_0_RDATA),
    .m_axi_matrix_b_0_RLAST(m_axi_matrix_b_0_RLAST),
    .m_axi_matrix_b_0_RID(m_axi_matrix_b_0_RID),
    .m_axi_matrix_b_0_RFIFONUM(m_axi_matrix_b_0_RFIFONUM),
    .m_axi_matrix_b_0_RUSER(m_axi_matrix_b_0_RUSER),
    .m_axi_matrix_b_0_RRESP(m_axi_matrix_b_0_RRESP),
    .m_axi_matrix_b_0_BVALID(1'b0),
    .m_axi_matrix_b_0_BREADY(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_BREADY),
    .m_axi_matrix_b_0_BRESP(2'd0),
    .m_axi_matrix_b_0_BID(1'd0),
    .m_axi_matrix_b_0_BUSER(1'd0),
    .matrix_in_2(matrix_in_2),
    .p_read(1'd0),
    .p_read2(1'd0),
    .p_read6(1'd0),
    .p_read10(1'd0),
    .p_read14(1'd0),
    .p_read18(1'd0),
    .p_read22(1'd0),
    .p_read26(1'd0),
    .p_read30(1'd0),
    .p_read34(1'd0),
    .p_read38(1'd0),
    .p_read42(1'd0),
    .p_read46(1'd0),
    .p_read50(1'd0),
    .p_read54(1'd0),
    .p_read58(1'd0),
    .ap_return_0(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_0),
    .ap_return_1(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_1),
    .ap_return_2(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_2),
    .ap_return_3(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_3),
    .ap_return_4(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_4),
    .ap_return_5(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_5),
    .ap_return_6(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_6),
    .ap_return_7(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_7),
    .ap_return_8(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_8),
    .ap_return_9(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_9),
    .ap_return_10(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_10),
    .ap_return_11(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_11),
    .ap_return_12(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_12),
    .ap_return_13(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_13),
    .ap_return_14(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_14),
    .ap_return_15(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_15)
);

MatrixMult_NoCache_matrixStitcher11 matrixStitcher11_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(matrixStitcher11_U0_ap_start),
    .ap_done(matrixStitcher11_U0_ap_done),
    .ap_continue(matrixStitcher11_U0_ap_continue),
    .ap_idle(matrixStitcher11_U0_ap_idle),
    .ap_ready(matrixStitcher11_U0_ap_ready),
    .m_axi_matrix_c_0_AWVALID(matrixStitcher11_U0_m_axi_matrix_c_0_AWVALID),
    .m_axi_matrix_c_0_AWREADY(m_axi_matrix_c_0_AWREADY),
    .m_axi_matrix_c_0_AWADDR(matrixStitcher11_U0_m_axi_matrix_c_0_AWADDR),
    .m_axi_matrix_c_0_AWID(matrixStitcher11_U0_m_axi_matrix_c_0_AWID),
    .m_axi_matrix_c_0_AWLEN(matrixStitcher11_U0_m_axi_matrix_c_0_AWLEN),
    .m_axi_matrix_c_0_AWSIZE(matrixStitcher11_U0_m_axi_matrix_c_0_AWSIZE),
    .m_axi_matrix_c_0_AWBURST(matrixStitcher11_U0_m_axi_matrix_c_0_AWBURST),
    .m_axi_matrix_c_0_AWLOCK(matrixStitcher11_U0_m_axi_matrix_c_0_AWLOCK),
    .m_axi_matrix_c_0_AWCACHE(matrixStitcher11_U0_m_axi_matrix_c_0_AWCACHE),
    .m_axi_matrix_c_0_AWPROT(matrixStitcher11_U0_m_axi_matrix_c_0_AWPROT),
    .m_axi_matrix_c_0_AWQOS(matrixStitcher11_U0_m_axi_matrix_c_0_AWQOS),
    .m_axi_matrix_c_0_AWREGION(matrixStitcher11_U0_m_axi_matrix_c_0_AWREGION),
    .m_axi_matrix_c_0_AWUSER(matrixStitcher11_U0_m_axi_matrix_c_0_AWUSER),
    .m_axi_matrix_c_0_WVALID(matrixStitcher11_U0_m_axi_matrix_c_0_WVALID),
    .m_axi_matrix_c_0_WREADY(m_axi_matrix_c_0_WREADY),
    .m_axi_matrix_c_0_WDATA(matrixStitcher11_U0_m_axi_matrix_c_0_WDATA),
    .m_axi_matrix_c_0_WSTRB(matrixStitcher11_U0_m_axi_matrix_c_0_WSTRB),
    .m_axi_matrix_c_0_WLAST(matrixStitcher11_U0_m_axi_matrix_c_0_WLAST),
    .m_axi_matrix_c_0_WID(matrixStitcher11_U0_m_axi_matrix_c_0_WID),
    .m_axi_matrix_c_0_WUSER(matrixStitcher11_U0_m_axi_matrix_c_0_WUSER),
    .m_axi_matrix_c_0_ARVALID(matrixStitcher11_U0_m_axi_matrix_c_0_ARVALID),
    .m_axi_matrix_c_0_ARREADY(1'b0),
    .m_axi_matrix_c_0_ARADDR(matrixStitcher11_U0_m_axi_matrix_c_0_ARADDR),
    .m_axi_matrix_c_0_ARID(matrixStitcher11_U0_m_axi_matrix_c_0_ARID),
    .m_axi_matrix_c_0_ARLEN(matrixStitcher11_U0_m_axi_matrix_c_0_ARLEN),
    .m_axi_matrix_c_0_ARSIZE(matrixStitcher11_U0_m_axi_matrix_c_0_ARSIZE),
    .m_axi_matrix_c_0_ARBURST(matrixStitcher11_U0_m_axi_matrix_c_0_ARBURST),
    .m_axi_matrix_c_0_ARLOCK(matrixStitcher11_U0_m_axi_matrix_c_0_ARLOCK),
    .m_axi_matrix_c_0_ARCACHE(matrixStitcher11_U0_m_axi_matrix_c_0_ARCACHE),
    .m_axi_matrix_c_0_ARPROT(matrixStitcher11_U0_m_axi_matrix_c_0_ARPROT),
    .m_axi_matrix_c_0_ARQOS(matrixStitcher11_U0_m_axi_matrix_c_0_ARQOS),
    .m_axi_matrix_c_0_ARREGION(matrixStitcher11_U0_m_axi_matrix_c_0_ARREGION),
    .m_axi_matrix_c_0_ARUSER(matrixStitcher11_U0_m_axi_matrix_c_0_ARUSER),
    .m_axi_matrix_c_0_RVALID(1'b0),
    .m_axi_matrix_c_0_RREADY(matrixStitcher11_U0_m_axi_matrix_c_0_RREADY),
    .m_axi_matrix_c_0_RDATA(32'd0),
    .m_axi_matrix_c_0_RLAST(1'b0),
    .m_axi_matrix_c_0_RID(1'd0),
    .m_axi_matrix_c_0_RFIFONUM(12'd0),
    .m_axi_matrix_c_0_RUSER(1'd0),
    .m_axi_matrix_c_0_RRESP(2'd0),
    .m_axi_matrix_c_0_BVALID(m_axi_matrix_c_0_BVALID),
    .m_axi_matrix_c_0_BREADY(matrixStitcher11_U0_m_axi_matrix_c_0_BREADY),
    .m_axi_matrix_c_0_BRESP(m_axi_matrix_c_0_BRESP),
    .m_axi_matrix_c_0_BID(m_axi_matrix_c_0_BID),
    .m_axi_matrix_c_0_BUSER(m_axi_matrix_c_0_BUSER),
    .ap_ce(1'b1),
    .p_read(Matrix_4x4_final_dout),
    .p_read1(Matrix_4x4_final_1_dout),
    .p_read2(Matrix_4x4_final_2_dout),
    .p_read3(Matrix_4x4_final_3_dout),
    .p_read4(Matrix_4x4_final_4_dout),
    .p_read5(Matrix_4x4_final_5_dout),
    .p_read6(Matrix_4x4_final_6_dout),
    .p_read7(Matrix_4x4_final_7_dout),
    .p_read8(Matrix_4x4_final_8_dout),
    .p_read9(Matrix_4x4_final_9_dout),
    .p_read10(Matrix_4x4_final_10_dout),
    .p_read11(Matrix_4x4_final_11_dout),
    .p_read12(Matrix_4x4_final_12_dout),
    .p_read13(Matrix_4x4_final_13_dout),
    .p_read14(Matrix_4x4_final_14_dout),
    .p_read15(Matrix_4x4_final15_dout),
    .size(size),
    .matrix_out(matrix_out)
);

MatrixMult_NoCache_fifo_w32_d2_S Matrix_4x4_final_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_0),
    .if_full_n(Matrix_4x4_final_full_n),
    .if_write(ap_channel_done_Matrix_4x4_final15),
    .if_dout(Matrix_4x4_final_dout),
    .if_empty_n(Matrix_4x4_final_empty_n),
    .if_read(matrixStitcher11_U0_ap_ready),
    .if_num_data_valid(Matrix_4x4_final_num_data_valid),
    .if_fifo_cap(Matrix_4x4_final_fifo_cap)
);

MatrixMult_NoCache_fifo_w32_d2_S Matrix_4x4_final_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_1),
    .if_full_n(Matrix_4x4_final_1_full_n),
    .if_write(ap_channel_done_Matrix_4x4_final15),
    .if_dout(Matrix_4x4_final_1_dout),
    .if_empty_n(Matrix_4x4_final_1_empty_n),
    .if_read(matrixStitcher11_U0_ap_ready),
    .if_num_data_valid(Matrix_4x4_final_1_num_data_valid),
    .if_fifo_cap(Matrix_4x4_final_1_fifo_cap)
);

MatrixMult_NoCache_fifo_w32_d2_S Matrix_4x4_final_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_2),
    .if_full_n(Matrix_4x4_final_2_full_n),
    .if_write(ap_channel_done_Matrix_4x4_final15),
    .if_dout(Matrix_4x4_final_2_dout),
    .if_empty_n(Matrix_4x4_final_2_empty_n),
    .if_read(matrixStitcher11_U0_ap_ready),
    .if_num_data_valid(Matrix_4x4_final_2_num_data_valid),
    .if_fifo_cap(Matrix_4x4_final_2_fifo_cap)
);

MatrixMult_NoCache_fifo_w32_d2_S Matrix_4x4_final_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_3),
    .if_full_n(Matrix_4x4_final_3_full_n),
    .if_write(ap_channel_done_Matrix_4x4_final15),
    .if_dout(Matrix_4x4_final_3_dout),
    .if_empty_n(Matrix_4x4_final_3_empty_n),
    .if_read(matrixStitcher11_U0_ap_ready),
    .if_num_data_valid(Matrix_4x4_final_3_num_data_valid),
    .if_fifo_cap(Matrix_4x4_final_3_fifo_cap)
);

MatrixMult_NoCache_fifo_w32_d2_S Matrix_4x4_final_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_4),
    .if_full_n(Matrix_4x4_final_4_full_n),
    .if_write(ap_channel_done_Matrix_4x4_final15),
    .if_dout(Matrix_4x4_final_4_dout),
    .if_empty_n(Matrix_4x4_final_4_empty_n),
    .if_read(matrixStitcher11_U0_ap_ready),
    .if_num_data_valid(Matrix_4x4_final_4_num_data_valid),
    .if_fifo_cap(Matrix_4x4_final_4_fifo_cap)
);

MatrixMult_NoCache_fifo_w32_d2_S Matrix_4x4_final_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_5),
    .if_full_n(Matrix_4x4_final_5_full_n),
    .if_write(ap_channel_done_Matrix_4x4_final15),
    .if_dout(Matrix_4x4_final_5_dout),
    .if_empty_n(Matrix_4x4_final_5_empty_n),
    .if_read(matrixStitcher11_U0_ap_ready),
    .if_num_data_valid(Matrix_4x4_final_5_num_data_valid),
    .if_fifo_cap(Matrix_4x4_final_5_fifo_cap)
);

MatrixMult_NoCache_fifo_w32_d2_S Matrix_4x4_final_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_6),
    .if_full_n(Matrix_4x4_final_6_full_n),
    .if_write(ap_channel_done_Matrix_4x4_final15),
    .if_dout(Matrix_4x4_final_6_dout),
    .if_empty_n(Matrix_4x4_final_6_empty_n),
    .if_read(matrixStitcher11_U0_ap_ready),
    .if_num_data_valid(Matrix_4x4_final_6_num_data_valid),
    .if_fifo_cap(Matrix_4x4_final_6_fifo_cap)
);

MatrixMult_NoCache_fifo_w32_d2_S Matrix_4x4_final_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_7),
    .if_full_n(Matrix_4x4_final_7_full_n),
    .if_write(ap_channel_done_Matrix_4x4_final15),
    .if_dout(Matrix_4x4_final_7_dout),
    .if_empty_n(Matrix_4x4_final_7_empty_n),
    .if_read(matrixStitcher11_U0_ap_ready),
    .if_num_data_valid(Matrix_4x4_final_7_num_data_valid),
    .if_fifo_cap(Matrix_4x4_final_7_fifo_cap)
);

MatrixMult_NoCache_fifo_w32_d2_S Matrix_4x4_final_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_8),
    .if_full_n(Matrix_4x4_final_8_full_n),
    .if_write(ap_channel_done_Matrix_4x4_final15),
    .if_dout(Matrix_4x4_final_8_dout),
    .if_empty_n(Matrix_4x4_final_8_empty_n),
    .if_read(matrixStitcher11_U0_ap_ready),
    .if_num_data_valid(Matrix_4x4_final_8_num_data_valid),
    .if_fifo_cap(Matrix_4x4_final_8_fifo_cap)
);

MatrixMult_NoCache_fifo_w32_d2_S Matrix_4x4_final_9_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_9),
    .if_full_n(Matrix_4x4_final_9_full_n),
    .if_write(ap_channel_done_Matrix_4x4_final15),
    .if_dout(Matrix_4x4_final_9_dout),
    .if_empty_n(Matrix_4x4_final_9_empty_n),
    .if_read(matrixStitcher11_U0_ap_ready),
    .if_num_data_valid(Matrix_4x4_final_9_num_data_valid),
    .if_fifo_cap(Matrix_4x4_final_9_fifo_cap)
);

MatrixMult_NoCache_fifo_w32_d2_S Matrix_4x4_final_10_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_10),
    .if_full_n(Matrix_4x4_final_10_full_n),
    .if_write(ap_channel_done_Matrix_4x4_final15),
    .if_dout(Matrix_4x4_final_10_dout),
    .if_empty_n(Matrix_4x4_final_10_empty_n),
    .if_read(matrixStitcher11_U0_ap_ready),
    .if_num_data_valid(Matrix_4x4_final_10_num_data_valid),
    .if_fifo_cap(Matrix_4x4_final_10_fifo_cap)
);

MatrixMult_NoCache_fifo_w32_d2_S Matrix_4x4_final_11_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_11),
    .if_full_n(Matrix_4x4_final_11_full_n),
    .if_write(ap_channel_done_Matrix_4x4_final15),
    .if_dout(Matrix_4x4_final_11_dout),
    .if_empty_n(Matrix_4x4_final_11_empty_n),
    .if_read(matrixStitcher11_U0_ap_ready),
    .if_num_data_valid(Matrix_4x4_final_11_num_data_valid),
    .if_fifo_cap(Matrix_4x4_final_11_fifo_cap)
);

MatrixMult_NoCache_fifo_w32_d2_S Matrix_4x4_final_12_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_12),
    .if_full_n(Matrix_4x4_final_12_full_n),
    .if_write(ap_channel_done_Matrix_4x4_final15),
    .if_dout(Matrix_4x4_final_12_dout),
    .if_empty_n(Matrix_4x4_final_12_empty_n),
    .if_read(matrixStitcher11_U0_ap_ready),
    .if_num_data_valid(Matrix_4x4_final_12_num_data_valid),
    .if_fifo_cap(Matrix_4x4_final_12_fifo_cap)
);

MatrixMult_NoCache_fifo_w32_d2_S Matrix_4x4_final_13_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_13),
    .if_full_n(Matrix_4x4_final_13_full_n),
    .if_write(ap_channel_done_Matrix_4x4_final15),
    .if_dout(Matrix_4x4_final_13_dout),
    .if_empty_n(Matrix_4x4_final_13_empty_n),
    .if_read(matrixStitcher11_U0_ap_ready),
    .if_num_data_valid(Matrix_4x4_final_13_num_data_valid),
    .if_fifo_cap(Matrix_4x4_final_13_fifo_cap)
);

MatrixMult_NoCache_fifo_w32_d2_S Matrix_4x4_final_14_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_14),
    .if_full_n(Matrix_4x4_final_14_full_n),
    .if_write(ap_channel_done_Matrix_4x4_final15),
    .if_dout(Matrix_4x4_final_14_dout),
    .if_empty_n(Matrix_4x4_final_14_empty_n),
    .if_read(matrixStitcher11_U0_ap_ready),
    .if_num_data_valid(Matrix_4x4_final_14_num_data_valid),
    .if_fifo_cap(Matrix_4x4_final_14_fifo_cap)
);

MatrixMult_NoCache_fifo_w32_d2_S Matrix_4x4_final15_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_15),
    .if_full_n(Matrix_4x4_final15_full_n),
    .if_write(ap_channel_done_Matrix_4x4_final15),
    .if_dout(Matrix_4x4_final15_dout),
    .if_empty_n(Matrix_4x4_final15_empty_n),
    .if_read(matrixStitcher11_U0_ap_ready),
    .if_num_data_valid(Matrix_4x4_final15_num_data_valid),
    .if_fifo_cap(Matrix_4x4_final15_fifo_cap)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_Matrix_4x4_final15 <= 1'b0;
    end else begin
        if (((dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_done & dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_Matrix_4x4_final15 <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_Matrix_4x4_final15 <= ap_sync_channel_write_Matrix_4x4_final15;
        end
    end
end

assign ap_channel_done_Matrix_4x4_final15 = ((ap_sync_reg_channel_write_Matrix_4x4_final15 ^ 1'b1) & dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_done);

assign ap_done = matrixStitcher11_U0_ap_done;

assign ap_idle = (matrixStitcher11_U0_ap_idle & (1'b1 ^ Matrix_4x4_final_empty_n) & dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_idle);

assign ap_ready = dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_ready;

assign ap_sync_channel_write_Matrix_4x4_final15 = ((ap_channel_done_Matrix_4x4_final15 & Matrix_4x4_final15_full_n) | ap_sync_reg_channel_write_Matrix_4x4_final15);

assign dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_continue = ap_sync_channel_write_Matrix_4x4_final15;

assign dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_start = ap_start;

assign m_axi_matrix_a_0_ARADDR = dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARADDR;

assign m_axi_matrix_a_0_ARBURST = dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARBURST;

assign m_axi_matrix_a_0_ARCACHE = dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARCACHE;

assign m_axi_matrix_a_0_ARID = dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARID;

assign m_axi_matrix_a_0_ARLEN = dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARLEN;

assign m_axi_matrix_a_0_ARLOCK = dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARLOCK;

assign m_axi_matrix_a_0_ARPROT = dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARPROT;

assign m_axi_matrix_a_0_ARQOS = dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARQOS;

assign m_axi_matrix_a_0_ARREGION = dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARREGION;

assign m_axi_matrix_a_0_ARSIZE = dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARSIZE;

assign m_axi_matrix_a_0_ARUSER = dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARUSER;

assign m_axi_matrix_a_0_ARVALID = dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARVALID;

assign m_axi_matrix_a_0_AWADDR = 64'd0;

assign m_axi_matrix_a_0_AWBURST = 2'd0;

assign m_axi_matrix_a_0_AWCACHE = 4'd0;

assign m_axi_matrix_a_0_AWID = 1'd0;

assign m_axi_matrix_a_0_AWLEN = 32'd0;

assign m_axi_matrix_a_0_AWLOCK = 2'd0;

assign m_axi_matrix_a_0_AWPROT = 3'd0;

assign m_axi_matrix_a_0_AWQOS = 4'd0;

assign m_axi_matrix_a_0_AWREGION = 4'd0;

assign m_axi_matrix_a_0_AWSIZE = 3'd0;

assign m_axi_matrix_a_0_AWUSER = 1'd0;

assign m_axi_matrix_a_0_AWVALID = 1'b0;

assign m_axi_matrix_a_0_BREADY = 1'b0;

assign m_axi_matrix_a_0_RREADY = dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_RREADY;

assign m_axi_matrix_a_0_WDATA = 16'd0;

assign m_axi_matrix_a_0_WID = 1'd0;

assign m_axi_matrix_a_0_WLAST = 1'b0;

assign m_axi_matrix_a_0_WSTRB = 2'd0;

assign m_axi_matrix_a_0_WUSER = 1'd0;

assign m_axi_matrix_a_0_WVALID = 1'b0;

assign m_axi_matrix_b_0_ARADDR = dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARADDR;

assign m_axi_matrix_b_0_ARBURST = dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARBURST;

assign m_axi_matrix_b_0_ARCACHE = dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARCACHE;

assign m_axi_matrix_b_0_ARID = dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARID;

assign m_axi_matrix_b_0_ARLEN = dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARLEN;

assign m_axi_matrix_b_0_ARLOCK = dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARLOCK;

assign m_axi_matrix_b_0_ARPROT = dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARPROT;

assign m_axi_matrix_b_0_ARQOS = dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARQOS;

assign m_axi_matrix_b_0_ARREGION = dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARREGION;

assign m_axi_matrix_b_0_ARSIZE = dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARSIZE;

assign m_axi_matrix_b_0_ARUSER = dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARUSER;

assign m_axi_matrix_b_0_ARVALID = dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARVALID;

assign m_axi_matrix_b_0_AWADDR = 64'd0;

assign m_axi_matrix_b_0_AWBURST = 2'd0;

assign m_axi_matrix_b_0_AWCACHE = 4'd0;

assign m_axi_matrix_b_0_AWID = 1'd0;

assign m_axi_matrix_b_0_AWLEN = 32'd0;

assign m_axi_matrix_b_0_AWLOCK = 2'd0;

assign m_axi_matrix_b_0_AWPROT = 3'd0;

assign m_axi_matrix_b_0_AWQOS = 4'd0;

assign m_axi_matrix_b_0_AWREGION = 4'd0;

assign m_axi_matrix_b_0_AWSIZE = 3'd0;

assign m_axi_matrix_b_0_AWUSER = 1'd0;

assign m_axi_matrix_b_0_AWVALID = 1'b0;

assign m_axi_matrix_b_0_BREADY = 1'b0;

assign m_axi_matrix_b_0_RREADY = dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_RREADY;

assign m_axi_matrix_b_0_WDATA = 16'd0;

assign m_axi_matrix_b_0_WID = 1'd0;

assign m_axi_matrix_b_0_WLAST = 1'b0;

assign m_axi_matrix_b_0_WSTRB = 2'd0;

assign m_axi_matrix_b_0_WUSER = 1'd0;

assign m_axi_matrix_b_0_WVALID = 1'b0;

assign m_axi_matrix_c_0_ARADDR = 64'd0;

assign m_axi_matrix_c_0_ARBURST = 2'd0;

assign m_axi_matrix_c_0_ARCACHE = 4'd0;

assign m_axi_matrix_c_0_ARID = 1'd0;

assign m_axi_matrix_c_0_ARLEN = 32'd0;

assign m_axi_matrix_c_0_ARLOCK = 2'd0;

assign m_axi_matrix_c_0_ARPROT = 3'd0;

assign m_axi_matrix_c_0_ARQOS = 4'd0;

assign m_axi_matrix_c_0_ARREGION = 4'd0;

assign m_axi_matrix_c_0_ARSIZE = 3'd0;

assign m_axi_matrix_c_0_ARUSER = 1'd0;

assign m_axi_matrix_c_0_ARVALID = 1'b0;

assign m_axi_matrix_c_0_AWADDR = matrixStitcher11_U0_m_axi_matrix_c_0_AWADDR;

assign m_axi_matrix_c_0_AWBURST = matrixStitcher11_U0_m_axi_matrix_c_0_AWBURST;

assign m_axi_matrix_c_0_AWCACHE = matrixStitcher11_U0_m_axi_matrix_c_0_AWCACHE;

assign m_axi_matrix_c_0_AWID = matrixStitcher11_U0_m_axi_matrix_c_0_AWID;

assign m_axi_matrix_c_0_AWLEN = matrixStitcher11_U0_m_axi_matrix_c_0_AWLEN;

assign m_axi_matrix_c_0_AWLOCK = matrixStitcher11_U0_m_axi_matrix_c_0_AWLOCK;

assign m_axi_matrix_c_0_AWPROT = matrixStitcher11_U0_m_axi_matrix_c_0_AWPROT;

assign m_axi_matrix_c_0_AWQOS = matrixStitcher11_U0_m_axi_matrix_c_0_AWQOS;

assign m_axi_matrix_c_0_AWREGION = matrixStitcher11_U0_m_axi_matrix_c_0_AWREGION;

assign m_axi_matrix_c_0_AWSIZE = matrixStitcher11_U0_m_axi_matrix_c_0_AWSIZE;

assign m_axi_matrix_c_0_AWUSER = matrixStitcher11_U0_m_axi_matrix_c_0_AWUSER;

assign m_axi_matrix_c_0_AWVALID = matrixStitcher11_U0_m_axi_matrix_c_0_AWVALID;

assign m_axi_matrix_c_0_BREADY = matrixStitcher11_U0_m_axi_matrix_c_0_BREADY;

assign m_axi_matrix_c_0_RREADY = 1'b0;

assign m_axi_matrix_c_0_WDATA = matrixStitcher11_U0_m_axi_matrix_c_0_WDATA;

assign m_axi_matrix_c_0_WID = matrixStitcher11_U0_m_axi_matrix_c_0_WID;

assign m_axi_matrix_c_0_WLAST = matrixStitcher11_U0_m_axi_matrix_c_0_WLAST;

assign m_axi_matrix_c_0_WSTRB = matrixStitcher11_U0_m_axi_matrix_c_0_WSTRB;

assign m_axi_matrix_c_0_WUSER = matrixStitcher11_U0_m_axi_matrix_c_0_WUSER;

assign m_axi_matrix_c_0_WVALID = matrixStitcher11_U0_m_axi_matrix_c_0_WVALID;

assign matrixStitcher11_U0_ap_continue = ap_continue;

assign matrixStitcher11_U0_ap_start = Matrix_4x4_final_empty_n;

endmodule //MatrixMult_NoCache_dataflow_in_loop_VITIS_LOOP_24_1_1
