// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module MatrixMult_dataflow_parent_loop_proc (
        mul,
        size,
        m_axi_matrix_a_0_AWVALID,
        m_axi_matrix_a_0_AWREADY,
        m_axi_matrix_a_0_AWADDR,
        m_axi_matrix_a_0_AWID,
        m_axi_matrix_a_0_AWLEN,
        m_axi_matrix_a_0_AWSIZE,
        m_axi_matrix_a_0_AWBURST,
        m_axi_matrix_a_0_AWLOCK,
        m_axi_matrix_a_0_AWCACHE,
        m_axi_matrix_a_0_AWPROT,
        m_axi_matrix_a_0_AWQOS,
        m_axi_matrix_a_0_AWREGION,
        m_axi_matrix_a_0_AWUSER,
        m_axi_matrix_a_0_WVALID,
        m_axi_matrix_a_0_WREADY,
        m_axi_matrix_a_0_WDATA,
        m_axi_matrix_a_0_WSTRB,
        m_axi_matrix_a_0_WLAST,
        m_axi_matrix_a_0_WID,
        m_axi_matrix_a_0_WUSER,
        m_axi_matrix_a_0_ARVALID,
        m_axi_matrix_a_0_ARREADY,
        m_axi_matrix_a_0_ARADDR,
        m_axi_matrix_a_0_ARID,
        m_axi_matrix_a_0_ARLEN,
        m_axi_matrix_a_0_ARSIZE,
        m_axi_matrix_a_0_ARBURST,
        m_axi_matrix_a_0_ARLOCK,
        m_axi_matrix_a_0_ARCACHE,
        m_axi_matrix_a_0_ARPROT,
        m_axi_matrix_a_0_ARQOS,
        m_axi_matrix_a_0_ARREGION,
        m_axi_matrix_a_0_ARUSER,
        m_axi_matrix_a_0_RVALID,
        m_axi_matrix_a_0_RREADY,
        m_axi_matrix_a_0_RDATA,
        m_axi_matrix_a_0_RLAST,
        m_axi_matrix_a_0_RID,
        m_axi_matrix_a_0_RFIFONUM,
        m_axi_matrix_a_0_RUSER,
        m_axi_matrix_a_0_RRESP,
        m_axi_matrix_a_0_BVALID,
        m_axi_matrix_a_0_BREADY,
        m_axi_matrix_a_0_BRESP,
        m_axi_matrix_a_0_BID,
        m_axi_matrix_a_0_BUSER,
        matrix_in_1,
        m_axi_matrix_b_0_AWVALID,
        m_axi_matrix_b_0_AWREADY,
        m_axi_matrix_b_0_AWADDR,
        m_axi_matrix_b_0_AWID,
        m_axi_matrix_b_0_AWLEN,
        m_axi_matrix_b_0_AWSIZE,
        m_axi_matrix_b_0_AWBURST,
        m_axi_matrix_b_0_AWLOCK,
        m_axi_matrix_b_0_AWCACHE,
        m_axi_matrix_b_0_AWPROT,
        m_axi_matrix_b_0_AWQOS,
        m_axi_matrix_b_0_AWREGION,
        m_axi_matrix_b_0_AWUSER,
        m_axi_matrix_b_0_WVALID,
        m_axi_matrix_b_0_WREADY,
        m_axi_matrix_b_0_WDATA,
        m_axi_matrix_b_0_WSTRB,
        m_axi_matrix_b_0_WLAST,
        m_axi_matrix_b_0_WID,
        m_axi_matrix_b_0_WUSER,
        m_axi_matrix_b_0_ARVALID,
        m_axi_matrix_b_0_ARREADY,
        m_axi_matrix_b_0_ARADDR,
        m_axi_matrix_b_0_ARID,
        m_axi_matrix_b_0_ARLEN,
        m_axi_matrix_b_0_ARSIZE,
        m_axi_matrix_b_0_ARBURST,
        m_axi_matrix_b_0_ARLOCK,
        m_axi_matrix_b_0_ARCACHE,
        m_axi_matrix_b_0_ARPROT,
        m_axi_matrix_b_0_ARQOS,
        m_axi_matrix_b_0_ARREGION,
        m_axi_matrix_b_0_ARUSER,
        m_axi_matrix_b_0_RVALID,
        m_axi_matrix_b_0_RREADY,
        m_axi_matrix_b_0_RDATA,
        m_axi_matrix_b_0_RLAST,
        m_axi_matrix_b_0_RID,
        m_axi_matrix_b_0_RFIFONUM,
        m_axi_matrix_b_0_RUSER,
        m_axi_matrix_b_0_RRESP,
        m_axi_matrix_b_0_BVALID,
        m_axi_matrix_b_0_BREADY,
        m_axi_matrix_b_0_BRESP,
        m_axi_matrix_b_0_BID,
        m_axi_matrix_b_0_BUSER,
        matrix_in_2,
        m_axi_matrix_c_0_AWVALID,
        m_axi_matrix_c_0_AWREADY,
        m_axi_matrix_c_0_AWADDR,
        m_axi_matrix_c_0_AWID,
        m_axi_matrix_c_0_AWLEN,
        m_axi_matrix_c_0_AWSIZE,
        m_axi_matrix_c_0_AWBURST,
        m_axi_matrix_c_0_AWLOCK,
        m_axi_matrix_c_0_AWCACHE,
        m_axi_matrix_c_0_AWPROT,
        m_axi_matrix_c_0_AWQOS,
        m_axi_matrix_c_0_AWREGION,
        m_axi_matrix_c_0_AWUSER,
        m_axi_matrix_c_0_WVALID,
        m_axi_matrix_c_0_WREADY,
        m_axi_matrix_c_0_WDATA,
        m_axi_matrix_c_0_WSTRB,
        m_axi_matrix_c_0_WLAST,
        m_axi_matrix_c_0_WID,
        m_axi_matrix_c_0_WUSER,
        m_axi_matrix_c_0_ARVALID,
        m_axi_matrix_c_0_ARREADY,
        m_axi_matrix_c_0_ARADDR,
        m_axi_matrix_c_0_ARID,
        m_axi_matrix_c_0_ARLEN,
        m_axi_matrix_c_0_ARSIZE,
        m_axi_matrix_c_0_ARBURST,
        m_axi_matrix_c_0_ARLOCK,
        m_axi_matrix_c_0_ARCACHE,
        m_axi_matrix_c_0_ARPROT,
        m_axi_matrix_c_0_ARQOS,
        m_axi_matrix_c_0_ARREGION,
        m_axi_matrix_c_0_ARUSER,
        m_axi_matrix_c_0_RVALID,
        m_axi_matrix_c_0_RREADY,
        m_axi_matrix_c_0_RDATA,
        m_axi_matrix_c_0_RLAST,
        m_axi_matrix_c_0_RID,
        m_axi_matrix_c_0_RFIFONUM,
        m_axi_matrix_c_0_RUSER,
        m_axi_matrix_c_0_RRESP,
        m_axi_matrix_c_0_BVALID,
        m_axi_matrix_c_0_BREADY,
        m_axi_matrix_c_0_BRESP,
        m_axi_matrix_c_0_BID,
        m_axi_matrix_c_0_BUSER,
        matrix_out,
        ap_clk,
        ap_rst,
        size_ap_vld,
        matrix_in_1_ap_vld,
        matrix_in_2_ap_vld,
        matrix_out_ap_vld,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [27:0] mul;
input  [15:0] size;
output   m_axi_matrix_a_0_AWVALID;
input   m_axi_matrix_a_0_AWREADY;
output  [63:0] m_axi_matrix_a_0_AWADDR;
output  [0:0] m_axi_matrix_a_0_AWID;
output  [31:0] m_axi_matrix_a_0_AWLEN;
output  [2:0] m_axi_matrix_a_0_AWSIZE;
output  [1:0] m_axi_matrix_a_0_AWBURST;
output  [1:0] m_axi_matrix_a_0_AWLOCK;
output  [3:0] m_axi_matrix_a_0_AWCACHE;
output  [2:0] m_axi_matrix_a_0_AWPROT;
output  [3:0] m_axi_matrix_a_0_AWQOS;
output  [3:0] m_axi_matrix_a_0_AWREGION;
output  [0:0] m_axi_matrix_a_0_AWUSER;
output   m_axi_matrix_a_0_WVALID;
input   m_axi_matrix_a_0_WREADY;
output  [15:0] m_axi_matrix_a_0_WDATA;
output  [1:0] m_axi_matrix_a_0_WSTRB;
output   m_axi_matrix_a_0_WLAST;
output  [0:0] m_axi_matrix_a_0_WID;
output  [0:0] m_axi_matrix_a_0_WUSER;
output   m_axi_matrix_a_0_ARVALID;
input   m_axi_matrix_a_0_ARREADY;
output  [63:0] m_axi_matrix_a_0_ARADDR;
output  [0:0] m_axi_matrix_a_0_ARID;
output  [31:0] m_axi_matrix_a_0_ARLEN;
output  [2:0] m_axi_matrix_a_0_ARSIZE;
output  [1:0] m_axi_matrix_a_0_ARBURST;
output  [1:0] m_axi_matrix_a_0_ARLOCK;
output  [3:0] m_axi_matrix_a_0_ARCACHE;
output  [2:0] m_axi_matrix_a_0_ARPROT;
output  [3:0] m_axi_matrix_a_0_ARQOS;
output  [3:0] m_axi_matrix_a_0_ARREGION;
output  [0:0] m_axi_matrix_a_0_ARUSER;
input   m_axi_matrix_a_0_RVALID;
output   m_axi_matrix_a_0_RREADY;
input  [15:0] m_axi_matrix_a_0_RDATA;
input   m_axi_matrix_a_0_RLAST;
input  [0:0] m_axi_matrix_a_0_RID;
input  [12:0] m_axi_matrix_a_0_RFIFONUM;
input  [0:0] m_axi_matrix_a_0_RUSER;
input  [1:0] m_axi_matrix_a_0_RRESP;
input   m_axi_matrix_a_0_BVALID;
output   m_axi_matrix_a_0_BREADY;
input  [1:0] m_axi_matrix_a_0_BRESP;
input  [0:0] m_axi_matrix_a_0_BID;
input  [0:0] m_axi_matrix_a_0_BUSER;
input  [63:0] matrix_in_1;
output   m_axi_matrix_b_0_AWVALID;
input   m_axi_matrix_b_0_AWREADY;
output  [63:0] m_axi_matrix_b_0_AWADDR;
output  [0:0] m_axi_matrix_b_0_AWID;
output  [31:0] m_axi_matrix_b_0_AWLEN;
output  [2:0] m_axi_matrix_b_0_AWSIZE;
output  [1:0] m_axi_matrix_b_0_AWBURST;
output  [1:0] m_axi_matrix_b_0_AWLOCK;
output  [3:0] m_axi_matrix_b_0_AWCACHE;
output  [2:0] m_axi_matrix_b_0_AWPROT;
output  [3:0] m_axi_matrix_b_0_AWQOS;
output  [3:0] m_axi_matrix_b_0_AWREGION;
output  [0:0] m_axi_matrix_b_0_AWUSER;
output   m_axi_matrix_b_0_WVALID;
input   m_axi_matrix_b_0_WREADY;
output  [15:0] m_axi_matrix_b_0_WDATA;
output  [1:0] m_axi_matrix_b_0_WSTRB;
output   m_axi_matrix_b_0_WLAST;
output  [0:0] m_axi_matrix_b_0_WID;
output  [0:0] m_axi_matrix_b_0_WUSER;
output   m_axi_matrix_b_0_ARVALID;
input   m_axi_matrix_b_0_ARREADY;
output  [63:0] m_axi_matrix_b_0_ARADDR;
output  [0:0] m_axi_matrix_b_0_ARID;
output  [31:0] m_axi_matrix_b_0_ARLEN;
output  [2:0] m_axi_matrix_b_0_ARSIZE;
output  [1:0] m_axi_matrix_b_0_ARBURST;
output  [1:0] m_axi_matrix_b_0_ARLOCK;
output  [3:0] m_axi_matrix_b_0_ARCACHE;
output  [2:0] m_axi_matrix_b_0_ARPROT;
output  [3:0] m_axi_matrix_b_0_ARQOS;
output  [3:0] m_axi_matrix_b_0_ARREGION;
output  [0:0] m_axi_matrix_b_0_ARUSER;
input   m_axi_matrix_b_0_RVALID;
output   m_axi_matrix_b_0_RREADY;
input  [15:0] m_axi_matrix_b_0_RDATA;
input   m_axi_matrix_b_0_RLAST;
input  [0:0] m_axi_matrix_b_0_RID;
input  [12:0] m_axi_matrix_b_0_RFIFONUM;
input  [0:0] m_axi_matrix_b_0_RUSER;
input  [1:0] m_axi_matrix_b_0_RRESP;
input   m_axi_matrix_b_0_BVALID;
output   m_axi_matrix_b_0_BREADY;
input  [1:0] m_axi_matrix_b_0_BRESP;
input  [0:0] m_axi_matrix_b_0_BID;
input  [0:0] m_axi_matrix_b_0_BUSER;
input  [63:0] matrix_in_2;
output   m_axi_matrix_c_0_AWVALID;
input   m_axi_matrix_c_0_AWREADY;
output  [63:0] m_axi_matrix_c_0_AWADDR;
output  [0:0] m_axi_matrix_c_0_AWID;
output  [31:0] m_axi_matrix_c_0_AWLEN;
output  [2:0] m_axi_matrix_c_0_AWSIZE;
output  [1:0] m_axi_matrix_c_0_AWBURST;
output  [1:0] m_axi_matrix_c_0_AWLOCK;
output  [3:0] m_axi_matrix_c_0_AWCACHE;
output  [2:0] m_axi_matrix_c_0_AWPROT;
output  [3:0] m_axi_matrix_c_0_AWQOS;
output  [3:0] m_axi_matrix_c_0_AWREGION;
output  [0:0] m_axi_matrix_c_0_AWUSER;
output   m_axi_matrix_c_0_WVALID;
input   m_axi_matrix_c_0_WREADY;
output  [31:0] m_axi_matrix_c_0_WDATA;
output  [3:0] m_axi_matrix_c_0_WSTRB;
output   m_axi_matrix_c_0_WLAST;
output  [0:0] m_axi_matrix_c_0_WID;
output  [0:0] m_axi_matrix_c_0_WUSER;
output   m_axi_matrix_c_0_ARVALID;
input   m_axi_matrix_c_0_ARREADY;
output  [63:0] m_axi_matrix_c_0_ARADDR;
output  [0:0] m_axi_matrix_c_0_ARID;
output  [31:0] m_axi_matrix_c_0_ARLEN;
output  [2:0] m_axi_matrix_c_0_ARSIZE;
output  [1:0] m_axi_matrix_c_0_ARBURST;
output  [1:0] m_axi_matrix_c_0_ARLOCK;
output  [3:0] m_axi_matrix_c_0_ARCACHE;
output  [2:0] m_axi_matrix_c_0_ARPROT;
output  [3:0] m_axi_matrix_c_0_ARQOS;
output  [3:0] m_axi_matrix_c_0_ARREGION;
output  [0:0] m_axi_matrix_c_0_ARUSER;
input   m_axi_matrix_c_0_RVALID;
output   m_axi_matrix_c_0_RREADY;
input  [31:0] m_axi_matrix_c_0_RDATA;
input   m_axi_matrix_c_0_RLAST;
input  [0:0] m_axi_matrix_c_0_RID;
input  [11:0] m_axi_matrix_c_0_RFIFONUM;
input  [0:0] m_axi_matrix_c_0_RUSER;
input  [1:0] m_axi_matrix_c_0_RRESP;
input   m_axi_matrix_c_0_BVALID;
output   m_axi_matrix_c_0_BREADY;
input  [1:0] m_axi_matrix_c_0_BRESP;
input  [0:0] m_axi_matrix_c_0_BID;
input  [0:0] m_axi_matrix_c_0_BUSER;
input  [63:0] matrix_out;
input   ap_clk;
input   ap_rst;
input   size_ap_vld;
input   matrix_in_1_ap_vld;
input   matrix_in_2_ap_vld;
input   matrix_out_ap_vld;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

reg ap_done;
reg ap_ready;
reg ap_idle;

wire    dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWVALID;
wire   [63:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWADDR;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWID;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWLEN;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWSIZE;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWBURST;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWLOCK;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWCACHE;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWPROT;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWQOS;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWREGION;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWUSER;
wire    dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_WVALID;
wire   [15:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_WDATA;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_WSTRB;
wire    dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_WLAST;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_WID;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_WUSER;
wire    dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARVALID;
wire   [63:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARADDR;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARID;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARLEN;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARSIZE;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARBURST;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARLOCK;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARCACHE;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARPROT;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARQOS;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARREGION;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARUSER;
wire    dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_RREADY;
wire    dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_BREADY;
wire    dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWVALID;
wire   [63:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWADDR;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWID;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWLEN;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWSIZE;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWBURST;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWLOCK;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWCACHE;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWPROT;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWQOS;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWREGION;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWUSER;
wire    dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_WVALID;
wire   [15:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_WDATA;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_WSTRB;
wire    dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_WLAST;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_WID;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_WUSER;
wire    dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARVALID;
wire   [63:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARADDR;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARID;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARLEN;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARSIZE;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARBURST;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARLOCK;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARCACHE;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARPROT;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARQOS;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARREGION;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARUSER;
wire    dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_RREADY;
wire    dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_BREADY;
wire    dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWVALID;
wire   [63:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWADDR;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWID;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWLEN;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWSIZE;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWBURST;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWLOCK;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWCACHE;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWPROT;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWQOS;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWREGION;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWUSER;
wire    dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_WVALID;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_WDATA;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_WSTRB;
wire    dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_WLAST;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_WID;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_WUSER;
wire    dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARVALID;
wire   [63:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARADDR;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARID;
wire   [31:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARLEN;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARSIZE;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARBURST;
wire   [1:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARLOCK;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARCACHE;
wire   [2:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARPROT;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARQOS;
wire   [3:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARREGION;
wire   [0:0] dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARUSER;
wire    dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_RREADY;
wire    dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_BREADY;
wire    dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_start;
wire    dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_done;
wire    dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_ready;
wire    dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_idle;
reg    dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_continue;
reg   [27:0] loop_dataflow_input_count;
reg   [27:0] loop_dataflow_output_count;
wire   [27:0] ap_input_count_plus_step;
wire   [27:0] ap_output_count_plus_step;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 loop_dataflow_input_count = 28'd0;
#0 loop_dataflow_output_count = 28'd0;
end

MatrixMult_dataflow_in_loop_VITIS_LOOP_24_1_1 dataflow_in_loop_VITIS_LOOP_24_1_1_U0(
    .size(size),
    .m_axi_matrix_a_0_AWVALID(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWVALID),
    .m_axi_matrix_a_0_AWREADY(1'b0),
    .m_axi_matrix_a_0_AWADDR(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWADDR),
    .m_axi_matrix_a_0_AWID(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWID),
    .m_axi_matrix_a_0_AWLEN(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWLEN),
    .m_axi_matrix_a_0_AWSIZE(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWSIZE),
    .m_axi_matrix_a_0_AWBURST(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWBURST),
    .m_axi_matrix_a_0_AWLOCK(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWLOCK),
    .m_axi_matrix_a_0_AWCACHE(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWCACHE),
    .m_axi_matrix_a_0_AWPROT(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWPROT),
    .m_axi_matrix_a_0_AWQOS(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWQOS),
    .m_axi_matrix_a_0_AWREGION(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWREGION),
    .m_axi_matrix_a_0_AWUSER(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWUSER),
    .m_axi_matrix_a_0_WVALID(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_WVALID),
    .m_axi_matrix_a_0_WREADY(1'b0),
    .m_axi_matrix_a_0_WDATA(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_WDATA),
    .m_axi_matrix_a_0_WSTRB(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_WSTRB),
    .m_axi_matrix_a_0_WLAST(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_WLAST),
    .m_axi_matrix_a_0_WID(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_WID),
    .m_axi_matrix_a_0_WUSER(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_WUSER),
    .m_axi_matrix_a_0_ARVALID(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARVALID),
    .m_axi_matrix_a_0_ARREADY(m_axi_matrix_a_0_ARREADY),
    .m_axi_matrix_a_0_ARADDR(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARADDR),
    .m_axi_matrix_a_0_ARID(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARID),
    .m_axi_matrix_a_0_ARLEN(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARLEN),
    .m_axi_matrix_a_0_ARSIZE(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARSIZE),
    .m_axi_matrix_a_0_ARBURST(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARBURST),
    .m_axi_matrix_a_0_ARLOCK(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARLOCK),
    .m_axi_matrix_a_0_ARCACHE(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARCACHE),
    .m_axi_matrix_a_0_ARPROT(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARPROT),
    .m_axi_matrix_a_0_ARQOS(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARQOS),
    .m_axi_matrix_a_0_ARREGION(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARREGION),
    .m_axi_matrix_a_0_ARUSER(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARUSER),
    .m_axi_matrix_a_0_RVALID(m_axi_matrix_a_0_RVALID),
    .m_axi_matrix_a_0_RREADY(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_RREADY),
    .m_axi_matrix_a_0_RDATA(m_axi_matrix_a_0_RDATA),
    .m_axi_matrix_a_0_RLAST(m_axi_matrix_a_0_RLAST),
    .m_axi_matrix_a_0_RID(m_axi_matrix_a_0_RID),
    .m_axi_matrix_a_0_RFIFONUM(m_axi_matrix_a_0_RFIFONUM),
    .m_axi_matrix_a_0_RUSER(m_axi_matrix_a_0_RUSER),
    .m_axi_matrix_a_0_RRESP(m_axi_matrix_a_0_RRESP),
    .m_axi_matrix_a_0_BVALID(1'b0),
    .m_axi_matrix_a_0_BREADY(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_BREADY),
    .m_axi_matrix_a_0_BRESP(2'd0),
    .m_axi_matrix_a_0_BID(1'd0),
    .m_axi_matrix_a_0_BUSER(1'd0),
    .matrix_in_1(matrix_in_1),
    .m_axi_matrix_b_0_AWVALID(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWVALID),
    .m_axi_matrix_b_0_AWREADY(1'b0),
    .m_axi_matrix_b_0_AWADDR(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWADDR),
    .m_axi_matrix_b_0_AWID(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWID),
    .m_axi_matrix_b_0_AWLEN(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWLEN),
    .m_axi_matrix_b_0_AWSIZE(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWSIZE),
    .m_axi_matrix_b_0_AWBURST(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWBURST),
    .m_axi_matrix_b_0_AWLOCK(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWLOCK),
    .m_axi_matrix_b_0_AWCACHE(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWCACHE),
    .m_axi_matrix_b_0_AWPROT(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWPROT),
    .m_axi_matrix_b_0_AWQOS(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWQOS),
    .m_axi_matrix_b_0_AWREGION(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWREGION),
    .m_axi_matrix_b_0_AWUSER(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWUSER),
    .m_axi_matrix_b_0_WVALID(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_WVALID),
    .m_axi_matrix_b_0_WREADY(1'b0),
    .m_axi_matrix_b_0_WDATA(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_WDATA),
    .m_axi_matrix_b_0_WSTRB(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_WSTRB),
    .m_axi_matrix_b_0_WLAST(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_WLAST),
    .m_axi_matrix_b_0_WID(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_WID),
    .m_axi_matrix_b_0_WUSER(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_WUSER),
    .m_axi_matrix_b_0_ARVALID(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARVALID),
    .m_axi_matrix_b_0_ARREADY(m_axi_matrix_b_0_ARREADY),
    .m_axi_matrix_b_0_ARADDR(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARADDR),
    .m_axi_matrix_b_0_ARID(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARID),
    .m_axi_matrix_b_0_ARLEN(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARLEN),
    .m_axi_matrix_b_0_ARSIZE(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARSIZE),
    .m_axi_matrix_b_0_ARBURST(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARBURST),
    .m_axi_matrix_b_0_ARLOCK(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARLOCK),
    .m_axi_matrix_b_0_ARCACHE(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARCACHE),
    .m_axi_matrix_b_0_ARPROT(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARPROT),
    .m_axi_matrix_b_0_ARQOS(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARQOS),
    .m_axi_matrix_b_0_ARREGION(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARREGION),
    .m_axi_matrix_b_0_ARUSER(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARUSER),
    .m_axi_matrix_b_0_RVALID(m_axi_matrix_b_0_RVALID),
    .m_axi_matrix_b_0_RREADY(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_RREADY),
    .m_axi_matrix_b_0_RDATA(m_axi_matrix_b_0_RDATA),
    .m_axi_matrix_b_0_RLAST(m_axi_matrix_b_0_RLAST),
    .m_axi_matrix_b_0_RID(m_axi_matrix_b_0_RID),
    .m_axi_matrix_b_0_RFIFONUM(m_axi_matrix_b_0_RFIFONUM),
    .m_axi_matrix_b_0_RUSER(m_axi_matrix_b_0_RUSER),
    .m_axi_matrix_b_0_RRESP(m_axi_matrix_b_0_RRESP),
    .m_axi_matrix_b_0_BVALID(1'b0),
    .m_axi_matrix_b_0_BREADY(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_BREADY),
    .m_axi_matrix_b_0_BRESP(2'd0),
    .m_axi_matrix_b_0_BID(1'd0),
    .m_axi_matrix_b_0_BUSER(1'd0),
    .matrix_in_2(matrix_in_2),
    .m_axi_matrix_c_0_AWVALID(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWVALID),
    .m_axi_matrix_c_0_AWREADY(m_axi_matrix_c_0_AWREADY),
    .m_axi_matrix_c_0_AWADDR(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWADDR),
    .m_axi_matrix_c_0_AWID(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWID),
    .m_axi_matrix_c_0_AWLEN(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWLEN),
    .m_axi_matrix_c_0_AWSIZE(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWSIZE),
    .m_axi_matrix_c_0_AWBURST(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWBURST),
    .m_axi_matrix_c_0_AWLOCK(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWLOCK),
    .m_axi_matrix_c_0_AWCACHE(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWCACHE),
    .m_axi_matrix_c_0_AWPROT(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWPROT),
    .m_axi_matrix_c_0_AWQOS(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWQOS),
    .m_axi_matrix_c_0_AWREGION(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWREGION),
    .m_axi_matrix_c_0_AWUSER(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWUSER),
    .m_axi_matrix_c_0_WVALID(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_WVALID),
    .m_axi_matrix_c_0_WREADY(m_axi_matrix_c_0_WREADY),
    .m_axi_matrix_c_0_WDATA(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_WDATA),
    .m_axi_matrix_c_0_WSTRB(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_WSTRB),
    .m_axi_matrix_c_0_WLAST(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_WLAST),
    .m_axi_matrix_c_0_WID(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_WID),
    .m_axi_matrix_c_0_WUSER(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_WUSER),
    .m_axi_matrix_c_0_ARVALID(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARVALID),
    .m_axi_matrix_c_0_ARREADY(1'b0),
    .m_axi_matrix_c_0_ARADDR(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARADDR),
    .m_axi_matrix_c_0_ARID(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARID),
    .m_axi_matrix_c_0_ARLEN(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARLEN),
    .m_axi_matrix_c_0_ARSIZE(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARSIZE),
    .m_axi_matrix_c_0_ARBURST(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARBURST),
    .m_axi_matrix_c_0_ARLOCK(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARLOCK),
    .m_axi_matrix_c_0_ARCACHE(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARCACHE),
    .m_axi_matrix_c_0_ARPROT(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARPROT),
    .m_axi_matrix_c_0_ARQOS(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARQOS),
    .m_axi_matrix_c_0_ARREGION(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARREGION),
    .m_axi_matrix_c_0_ARUSER(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARUSER),
    .m_axi_matrix_c_0_RVALID(1'b0),
    .m_axi_matrix_c_0_RREADY(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_RREADY),
    .m_axi_matrix_c_0_RDATA(32'd0),
    .m_axi_matrix_c_0_RLAST(1'b0),
    .m_axi_matrix_c_0_RID(1'd0),
    .m_axi_matrix_c_0_RFIFONUM(12'd0),
    .m_axi_matrix_c_0_RUSER(1'd0),
    .m_axi_matrix_c_0_RRESP(2'd0),
    .m_axi_matrix_c_0_BVALID(m_axi_matrix_c_0_BVALID),
    .m_axi_matrix_c_0_BREADY(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_BREADY),
    .m_axi_matrix_c_0_BRESP(m_axi_matrix_c_0_BRESP),
    .m_axi_matrix_c_0_BID(m_axi_matrix_c_0_BID),
    .m_axi_matrix_c_0_BUSER(m_axi_matrix_c_0_BUSER),
    .matrix_out(matrix_out),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .size_ap_vld(size_ap_vld),
    .matrix_in_1_ap_vld(matrix_in_1_ap_vld),
    .matrix_in_2_ap_vld(matrix_in_2_ap_vld),
    .ap_start(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_start),
    .matrix_out_ap_vld(matrix_out_ap_vld),
    .ap_done(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_done),
    .ap_ready(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_ready),
    .ap_idle(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_idle),
    .ap_continue(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        loop_dataflow_input_count <= 28'd0;
    end else begin
        if ((~(mul == ap_input_count_plus_step) & (ap_start == 1'b1) & (dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_ready == 1'b1))) begin
            loop_dataflow_input_count <= ap_input_count_plus_step;
        end else if (((ap_start == 1'b1) & (dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_ready == 1'b1) & (mul == ap_input_count_plus_step))) begin
            loop_dataflow_input_count <= 28'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        loop_dataflow_output_count <= 28'd0;
    end else begin
        if ((~(mul == ap_output_count_plus_step) & (dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_continue == 1'b1) & (dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_done == 1'b1))) begin
            loop_dataflow_output_count <= ap_output_count_plus_step;
        end else if (((dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_continue == 1'b1) & (dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_done == 1'b1) & (mul == ap_output_count_plus_step))) begin
            loop_dataflow_output_count <= 28'd0;
        end
    end
end

always @ (*) begin
    if (((dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_done == 1'b1) & (mul == ap_output_count_plus_step))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((loop_dataflow_output_count == 28'd0) & (ap_start == 1'b0) & (dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_idle == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_ready == 1'b1) & (mul == ap_input_count_plus_step))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~(mul == ap_output_count_plus_step) | (ap_continue == 1'b1))) begin
        dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_continue = 1'b1;
    end else begin
        dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_continue = 1'b0;
    end
end

assign ap_input_count_plus_step = (loop_dataflow_input_count + 28'd1);

assign ap_output_count_plus_step = (loop_dataflow_output_count + 28'd1);

assign dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_start = ap_start;

assign m_axi_matrix_a_0_ARADDR = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARADDR;

assign m_axi_matrix_a_0_ARBURST = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARBURST;

assign m_axi_matrix_a_0_ARCACHE = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARCACHE;

assign m_axi_matrix_a_0_ARID = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARID;

assign m_axi_matrix_a_0_ARLEN = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARLEN;

assign m_axi_matrix_a_0_ARLOCK = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARLOCK;

assign m_axi_matrix_a_0_ARPROT = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARPROT;

assign m_axi_matrix_a_0_ARQOS = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARQOS;

assign m_axi_matrix_a_0_ARREGION = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARREGION;

assign m_axi_matrix_a_0_ARSIZE = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARSIZE;

assign m_axi_matrix_a_0_ARUSER = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARUSER;

assign m_axi_matrix_a_0_ARVALID = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARVALID;

assign m_axi_matrix_a_0_AWADDR = 64'd0;

assign m_axi_matrix_a_0_AWBURST = 2'd0;

assign m_axi_matrix_a_0_AWCACHE = 4'd0;

assign m_axi_matrix_a_0_AWID = 1'd0;

assign m_axi_matrix_a_0_AWLEN = 32'd0;

assign m_axi_matrix_a_0_AWLOCK = 2'd0;

assign m_axi_matrix_a_0_AWPROT = 3'd0;

assign m_axi_matrix_a_0_AWQOS = 4'd0;

assign m_axi_matrix_a_0_AWREGION = 4'd0;

assign m_axi_matrix_a_0_AWSIZE = 3'd0;

assign m_axi_matrix_a_0_AWUSER = 1'd0;

assign m_axi_matrix_a_0_AWVALID = 1'b0;

assign m_axi_matrix_a_0_BREADY = 1'b0;

assign m_axi_matrix_a_0_RREADY = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_RREADY;

assign m_axi_matrix_a_0_WDATA = 16'd0;

assign m_axi_matrix_a_0_WID = 1'd0;

assign m_axi_matrix_a_0_WLAST = 1'b0;

assign m_axi_matrix_a_0_WSTRB = 2'd0;

assign m_axi_matrix_a_0_WUSER = 1'd0;

assign m_axi_matrix_a_0_WVALID = 1'b0;

assign m_axi_matrix_b_0_ARADDR = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARADDR;

assign m_axi_matrix_b_0_ARBURST = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARBURST;

assign m_axi_matrix_b_0_ARCACHE = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARCACHE;

assign m_axi_matrix_b_0_ARID = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARID;

assign m_axi_matrix_b_0_ARLEN = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARLEN;

assign m_axi_matrix_b_0_ARLOCK = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARLOCK;

assign m_axi_matrix_b_0_ARPROT = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARPROT;

assign m_axi_matrix_b_0_ARQOS = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARQOS;

assign m_axi_matrix_b_0_ARREGION = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARREGION;

assign m_axi_matrix_b_0_ARSIZE = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARSIZE;

assign m_axi_matrix_b_0_ARUSER = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARUSER;

assign m_axi_matrix_b_0_ARVALID = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARVALID;

assign m_axi_matrix_b_0_AWADDR = 64'd0;

assign m_axi_matrix_b_0_AWBURST = 2'd0;

assign m_axi_matrix_b_0_AWCACHE = 4'd0;

assign m_axi_matrix_b_0_AWID = 1'd0;

assign m_axi_matrix_b_0_AWLEN = 32'd0;

assign m_axi_matrix_b_0_AWLOCK = 2'd0;

assign m_axi_matrix_b_0_AWPROT = 3'd0;

assign m_axi_matrix_b_0_AWQOS = 4'd0;

assign m_axi_matrix_b_0_AWREGION = 4'd0;

assign m_axi_matrix_b_0_AWSIZE = 3'd0;

assign m_axi_matrix_b_0_AWUSER = 1'd0;

assign m_axi_matrix_b_0_AWVALID = 1'b0;

assign m_axi_matrix_b_0_BREADY = 1'b0;

assign m_axi_matrix_b_0_RREADY = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_RREADY;

assign m_axi_matrix_b_0_WDATA = 16'd0;

assign m_axi_matrix_b_0_WID = 1'd0;

assign m_axi_matrix_b_0_WLAST = 1'b0;

assign m_axi_matrix_b_0_WSTRB = 2'd0;

assign m_axi_matrix_b_0_WUSER = 1'd0;

assign m_axi_matrix_b_0_WVALID = 1'b0;

assign m_axi_matrix_c_0_ARADDR = 64'd0;

assign m_axi_matrix_c_0_ARBURST = 2'd0;

assign m_axi_matrix_c_0_ARCACHE = 4'd0;

assign m_axi_matrix_c_0_ARID = 1'd0;

assign m_axi_matrix_c_0_ARLEN = 32'd0;

assign m_axi_matrix_c_0_ARLOCK = 2'd0;

assign m_axi_matrix_c_0_ARPROT = 3'd0;

assign m_axi_matrix_c_0_ARQOS = 4'd0;

assign m_axi_matrix_c_0_ARREGION = 4'd0;

assign m_axi_matrix_c_0_ARSIZE = 3'd0;

assign m_axi_matrix_c_0_ARUSER = 1'd0;

assign m_axi_matrix_c_0_ARVALID = 1'b0;

assign m_axi_matrix_c_0_AWADDR = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWADDR;

assign m_axi_matrix_c_0_AWBURST = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWBURST;

assign m_axi_matrix_c_0_AWCACHE = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWCACHE;

assign m_axi_matrix_c_0_AWID = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWID;

assign m_axi_matrix_c_0_AWLEN = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWLEN;

assign m_axi_matrix_c_0_AWLOCK = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWLOCK;

assign m_axi_matrix_c_0_AWPROT = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWPROT;

assign m_axi_matrix_c_0_AWQOS = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWQOS;

assign m_axi_matrix_c_0_AWREGION = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWREGION;

assign m_axi_matrix_c_0_AWSIZE = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWSIZE;

assign m_axi_matrix_c_0_AWUSER = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWUSER;

assign m_axi_matrix_c_0_AWVALID = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWVALID;

assign m_axi_matrix_c_0_BREADY = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_BREADY;

assign m_axi_matrix_c_0_RREADY = 1'b0;

assign m_axi_matrix_c_0_WDATA = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_WDATA;

assign m_axi_matrix_c_0_WID = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_WID;

assign m_axi_matrix_c_0_WLAST = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_WLAST;

assign m_axi_matrix_c_0_WSTRB = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_WSTRB;

assign m_axi_matrix_c_0_WUSER = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_WUSER;

assign m_axi_matrix_c_0_WVALID = dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_WVALID;

endmodule //MatrixMult_dataflow_parent_loop_proc
