-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity MatrixMult_matrixAdder is
port (
    ap_ready : OUT STD_LOGIC;
    input_matrix_0_0_val : IN STD_LOGIC_VECTOR (31 downto 0);
    input_matrix_0_1_val : IN STD_LOGIC_VECTOR (31 downto 0);
    input_matrix_0_2_val : IN STD_LOGIC_VECTOR (31 downto 0);
    input_matrix_0_3_val : IN STD_LOGIC_VECTOR (31 downto 0);
    input_matrix_1_0_val : IN STD_LOGIC_VECTOR (31 downto 0);
    input_matrix_1_1_val : IN STD_LOGIC_VECTOR (31 downto 0);
    input_matrix_1_2_val : IN STD_LOGIC_VECTOR (31 downto 0);
    input_matrix_1_3_val : IN STD_LOGIC_VECTOR (31 downto 0);
    input_matrix_2_0_val : IN STD_LOGIC_VECTOR (31 downto 0);
    input_matrix_2_1_val : IN STD_LOGIC_VECTOR (31 downto 0);
    input_matrix_2_2_val : IN STD_LOGIC_VECTOR (31 downto 0);
    input_matrix_2_3_val : IN STD_LOGIC_VECTOR (31 downto 0);
    input_matrix_3_0_val : IN STD_LOGIC_VECTOR (31 downto 0);
    input_matrix_3_1_val : IN STD_LOGIC_VECTOR (31 downto 0);
    input_matrix_3_2_val : IN STD_LOGIC_VECTOR (31 downto 0);
    input_matrix_3_3_val : IN STD_LOGIC_VECTOR (31 downto 0);
    output_matrix_read : IN STD_LOGIC_VECTOR (31 downto 0);
    output_matrix_read_31 : IN STD_LOGIC_VECTOR (31 downto 0);
    output_matrix_read_32 : IN STD_LOGIC_VECTOR (31 downto 0);
    output_matrix_read_33 : IN STD_LOGIC_VECTOR (31 downto 0);
    output_matrix_read_34 : IN STD_LOGIC_VECTOR (31 downto 0);
    output_matrix_read_35 : IN STD_LOGIC_VECTOR (31 downto 0);
    output_matrix_read_36 : IN STD_LOGIC_VECTOR (31 downto 0);
    output_matrix_read_37 : IN STD_LOGIC_VECTOR (31 downto 0);
    output_matrix_read_38 : IN STD_LOGIC_VECTOR (31 downto 0);
    output_matrix_read_39 : IN STD_LOGIC_VECTOR (31 downto 0);
    output_matrix_read_40 : IN STD_LOGIC_VECTOR (31 downto 0);
    output_matrix_read_41 : IN STD_LOGIC_VECTOR (31 downto 0);
    output_matrix_read_42 : IN STD_LOGIC_VECTOR (31 downto 0);
    output_matrix_read_43 : IN STD_LOGIC_VECTOR (31 downto 0);
    output_matrix_read_44 : IN STD_LOGIC_VECTOR (31 downto 0);
    output_matrix_read_45 : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of MatrixMult_matrixAdder is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal add_ln16_fu_268_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln16_48_fu_274_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln16_49_fu_280_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln16_50_fu_286_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln16_51_fu_292_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln16_52_fu_298_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln16_53_fu_304_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln16_54_fu_310_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln16_55_fu_316_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln16_56_fu_322_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln16_57_fu_328_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln16_58_fu_334_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln16_59_fu_340_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln16_60_fu_346_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln16_61_fu_352_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln16_62_fu_358_p2 : STD_LOGIC_VECTOR (31 downto 0);


begin



    add_ln16_48_fu_274_p2 <= std_logic_vector(unsigned(output_matrix_read_31) + unsigned(input_matrix_0_1_val));
    add_ln16_49_fu_280_p2 <= std_logic_vector(unsigned(output_matrix_read_32) + unsigned(input_matrix_0_2_val));
    add_ln16_50_fu_286_p2 <= std_logic_vector(unsigned(output_matrix_read_33) + unsigned(input_matrix_0_3_val));
    add_ln16_51_fu_292_p2 <= std_logic_vector(unsigned(output_matrix_read_34) + unsigned(input_matrix_1_0_val));
    add_ln16_52_fu_298_p2 <= std_logic_vector(unsigned(output_matrix_read_35) + unsigned(input_matrix_1_1_val));
    add_ln16_53_fu_304_p2 <= std_logic_vector(unsigned(output_matrix_read_36) + unsigned(input_matrix_1_2_val));
    add_ln16_54_fu_310_p2 <= std_logic_vector(unsigned(output_matrix_read_37) + unsigned(input_matrix_1_3_val));
    add_ln16_55_fu_316_p2 <= std_logic_vector(unsigned(output_matrix_read_38) + unsigned(input_matrix_2_0_val));
    add_ln16_56_fu_322_p2 <= std_logic_vector(unsigned(output_matrix_read_39) + unsigned(input_matrix_2_1_val));
    add_ln16_57_fu_328_p2 <= std_logic_vector(unsigned(output_matrix_read_40) + unsigned(input_matrix_2_2_val));
    add_ln16_58_fu_334_p2 <= std_logic_vector(unsigned(output_matrix_read_41) + unsigned(input_matrix_2_3_val));
    add_ln16_59_fu_340_p2 <= std_logic_vector(unsigned(output_matrix_read_42) + unsigned(input_matrix_3_0_val));
    add_ln16_60_fu_346_p2 <= std_logic_vector(unsigned(output_matrix_read_43) + unsigned(input_matrix_3_1_val));
    add_ln16_61_fu_352_p2 <= std_logic_vector(unsigned(output_matrix_read_44) + unsigned(input_matrix_3_2_val));
    add_ln16_62_fu_358_p2 <= std_logic_vector(unsigned(output_matrix_read_45) + unsigned(input_matrix_3_3_val));
    add_ln16_fu_268_p2 <= std_logic_vector(unsigned(output_matrix_read) + unsigned(input_matrix_0_0_val));
    ap_ready <= ap_const_logic_1;
    ap_return_0 <= add_ln16_fu_268_p2;
    ap_return_1 <= add_ln16_48_fu_274_p2;
    ap_return_10 <= add_ln16_57_fu_328_p2;
    ap_return_11 <= add_ln16_58_fu_334_p2;
    ap_return_12 <= add_ln16_59_fu_340_p2;
    ap_return_13 <= add_ln16_60_fu_346_p2;
    ap_return_14 <= add_ln16_61_fu_352_p2;
    ap_return_15 <= add_ln16_62_fu_358_p2;
    ap_return_2 <= add_ln16_49_fu_280_p2;
    ap_return_3 <= add_ln16_50_fu_286_p2;
    ap_return_4 <= add_ln16_51_fu_292_p2;
    ap_return_5 <= add_ln16_52_fu_298_p2;
    ap_return_6 <= add_ln16_53_fu_304_p2;
    ap_return_7 <= add_ln16_54_fu_310_p2;
    ap_return_8 <= add_ln16_55_fu_316_p2;
    ap_return_9 <= add_ln16_56_fu_322_p2;
end behav;
