-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity MatrixMult_NoCache_dataflow_in_loop_VITIS_LOOP_24_1_1 is
port (
    size : IN STD_LOGIC_VECTOR (15 downto 0);
    m_axi_matrix_a_0_AWVALID : OUT STD_LOGIC;
    m_axi_matrix_a_0_AWREADY : IN STD_LOGIC;
    m_axi_matrix_a_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_matrix_a_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_a_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_matrix_a_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_matrix_a_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_a_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_a_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_matrix_a_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_matrix_a_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_matrix_a_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_matrix_a_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_a_0_WVALID : OUT STD_LOGIC;
    m_axi_matrix_a_0_WREADY : IN STD_LOGIC;
    m_axi_matrix_a_0_WDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    m_axi_matrix_a_0_WSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_a_0_WLAST : OUT STD_LOGIC;
    m_axi_matrix_a_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_a_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_a_0_ARVALID : OUT STD_LOGIC;
    m_axi_matrix_a_0_ARREADY : IN STD_LOGIC;
    m_axi_matrix_a_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_matrix_a_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_a_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_matrix_a_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_matrix_a_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_a_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_a_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_matrix_a_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_matrix_a_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_matrix_a_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_matrix_a_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_a_0_RVALID : IN STD_LOGIC;
    m_axi_matrix_a_0_RREADY : OUT STD_LOGIC;
    m_axi_matrix_a_0_RDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    m_axi_matrix_a_0_RLAST : IN STD_LOGIC;
    m_axi_matrix_a_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_a_0_RFIFONUM : IN STD_LOGIC_VECTOR (12 downto 0);
    m_axi_matrix_a_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_a_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_a_0_BVALID : IN STD_LOGIC;
    m_axi_matrix_a_0_BREADY : OUT STD_LOGIC;
    m_axi_matrix_a_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_a_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_a_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    matrix_in_1 : IN STD_LOGIC_VECTOR (63 downto 0);
    m_axi_matrix_b_0_AWVALID : OUT STD_LOGIC;
    m_axi_matrix_b_0_AWREADY : IN STD_LOGIC;
    m_axi_matrix_b_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_matrix_b_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_b_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_matrix_b_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_matrix_b_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_b_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_b_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_matrix_b_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_matrix_b_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_matrix_b_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_matrix_b_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_b_0_WVALID : OUT STD_LOGIC;
    m_axi_matrix_b_0_WREADY : IN STD_LOGIC;
    m_axi_matrix_b_0_WDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    m_axi_matrix_b_0_WSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_b_0_WLAST : OUT STD_LOGIC;
    m_axi_matrix_b_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_b_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_b_0_ARVALID : OUT STD_LOGIC;
    m_axi_matrix_b_0_ARREADY : IN STD_LOGIC;
    m_axi_matrix_b_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_matrix_b_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_b_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_matrix_b_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_matrix_b_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_b_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_b_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_matrix_b_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_matrix_b_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_matrix_b_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_matrix_b_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_b_0_RVALID : IN STD_LOGIC;
    m_axi_matrix_b_0_RREADY : OUT STD_LOGIC;
    m_axi_matrix_b_0_RDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    m_axi_matrix_b_0_RLAST : IN STD_LOGIC;
    m_axi_matrix_b_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_b_0_RFIFONUM : IN STD_LOGIC_VECTOR (12 downto 0);
    m_axi_matrix_b_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_b_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_b_0_BVALID : IN STD_LOGIC;
    m_axi_matrix_b_0_BREADY : OUT STD_LOGIC;
    m_axi_matrix_b_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_b_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_b_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    matrix_in_2 : IN STD_LOGIC_VECTOR (63 downto 0);
    m_axi_matrix_c_0_AWVALID : OUT STD_LOGIC;
    m_axi_matrix_c_0_AWREADY : IN STD_LOGIC;
    m_axi_matrix_c_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_matrix_c_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_c_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_matrix_c_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_matrix_c_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_c_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_c_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_matrix_c_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_matrix_c_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_matrix_c_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_matrix_c_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_c_0_WVALID : OUT STD_LOGIC;
    m_axi_matrix_c_0_WREADY : IN STD_LOGIC;
    m_axi_matrix_c_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_matrix_c_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_matrix_c_0_WLAST : OUT STD_LOGIC;
    m_axi_matrix_c_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_c_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_c_0_ARVALID : OUT STD_LOGIC;
    m_axi_matrix_c_0_ARREADY : IN STD_LOGIC;
    m_axi_matrix_c_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_matrix_c_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_c_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_matrix_c_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_matrix_c_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_c_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_c_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_matrix_c_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_matrix_c_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_matrix_c_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_matrix_c_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_c_0_RVALID : IN STD_LOGIC;
    m_axi_matrix_c_0_RREADY : OUT STD_LOGIC;
    m_axi_matrix_c_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_matrix_c_0_RLAST : IN STD_LOGIC;
    m_axi_matrix_c_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_c_0_RFIFONUM : IN STD_LOGIC_VECTOR (11 downto 0);
    m_axi_matrix_c_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_c_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_c_0_BVALID : IN STD_LOGIC;
    m_axi_matrix_c_0_BREADY : OUT STD_LOGIC;
    m_axi_matrix_c_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_c_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_c_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    matrix_out : IN STD_LOGIC_VECTOR (63 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    size_ap_vld : IN STD_LOGIC;
    matrix_in_1_ap_vld : IN STD_LOGIC;
    matrix_in_2_ap_vld : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    matrix_out_ap_vld : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of MatrixMult_NoCache_dataflow_in_loop_VITIS_LOOP_24_1_1 is 
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_start : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_done : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_continue : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_idle : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_ready : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWVALID : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_WVALID : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_WDATA : STD_LOGIC_VECTOR (15 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_WSTRB : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_WLAST : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARVALID : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_RREADY : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_BREADY : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWVALID : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_WVALID : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_WDATA : STD_LOGIC_VECTOR (15 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_WSTRB : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_WLAST : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARVALID : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_RREADY : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_BREADY : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_0 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_1 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_2 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_3 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_4 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_5 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_6 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_7 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_8 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_9 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_10 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_11 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_12 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_13 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_14 : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_15 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_channel_done_Matrix_4x4_final15 : STD_LOGIC;
    signal Matrix_4x4_final15_full_n : STD_LOGIC;
    signal ap_sync_reg_channel_write_Matrix_4x4_final15 : STD_LOGIC := '0';
    signal ap_sync_channel_write_Matrix_4x4_final15 : STD_LOGIC;
    signal matrixStitcher11_U0_ap_start : STD_LOGIC;
    signal matrixStitcher11_U0_ap_done : STD_LOGIC;
    signal matrixStitcher11_U0_ap_continue : STD_LOGIC;
    signal matrixStitcher11_U0_ap_idle : STD_LOGIC;
    signal matrixStitcher11_U0_ap_ready : STD_LOGIC;
    signal matrixStitcher11_U0_m_axi_matrix_c_0_AWVALID : STD_LOGIC;
    signal matrixStitcher11_U0_m_axi_matrix_c_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal matrixStitcher11_U0_m_axi_matrix_c_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal matrixStitcher11_U0_m_axi_matrix_c_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal matrixStitcher11_U0_m_axi_matrix_c_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal matrixStitcher11_U0_m_axi_matrix_c_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal matrixStitcher11_U0_m_axi_matrix_c_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal matrixStitcher11_U0_m_axi_matrix_c_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal matrixStitcher11_U0_m_axi_matrix_c_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal matrixStitcher11_U0_m_axi_matrix_c_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal matrixStitcher11_U0_m_axi_matrix_c_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal matrixStitcher11_U0_m_axi_matrix_c_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal matrixStitcher11_U0_m_axi_matrix_c_0_WVALID : STD_LOGIC;
    signal matrixStitcher11_U0_m_axi_matrix_c_0_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal matrixStitcher11_U0_m_axi_matrix_c_0_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal matrixStitcher11_U0_m_axi_matrix_c_0_WLAST : STD_LOGIC;
    signal matrixStitcher11_U0_m_axi_matrix_c_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal matrixStitcher11_U0_m_axi_matrix_c_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal matrixStitcher11_U0_m_axi_matrix_c_0_ARVALID : STD_LOGIC;
    signal matrixStitcher11_U0_m_axi_matrix_c_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal matrixStitcher11_U0_m_axi_matrix_c_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal matrixStitcher11_U0_m_axi_matrix_c_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal matrixStitcher11_U0_m_axi_matrix_c_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal matrixStitcher11_U0_m_axi_matrix_c_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal matrixStitcher11_U0_m_axi_matrix_c_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal matrixStitcher11_U0_m_axi_matrix_c_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal matrixStitcher11_U0_m_axi_matrix_c_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal matrixStitcher11_U0_m_axi_matrix_c_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal matrixStitcher11_U0_m_axi_matrix_c_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal matrixStitcher11_U0_m_axi_matrix_c_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal matrixStitcher11_U0_m_axi_matrix_c_0_RREADY : STD_LOGIC;
    signal matrixStitcher11_U0_m_axi_matrix_c_0_BREADY : STD_LOGIC;
    signal Matrix_4x4_final_full_n : STD_LOGIC;
    signal Matrix_4x4_final_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal Matrix_4x4_final_empty_n : STD_LOGIC;
    signal Matrix_4x4_final_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal Matrix_4x4_final_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal Matrix_4x4_final_1_full_n : STD_LOGIC;
    signal Matrix_4x4_final_1_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal Matrix_4x4_final_1_empty_n : STD_LOGIC;
    signal Matrix_4x4_final_1_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal Matrix_4x4_final_1_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal Matrix_4x4_final_2_full_n : STD_LOGIC;
    signal Matrix_4x4_final_2_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal Matrix_4x4_final_2_empty_n : STD_LOGIC;
    signal Matrix_4x4_final_2_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal Matrix_4x4_final_2_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal Matrix_4x4_final_3_full_n : STD_LOGIC;
    signal Matrix_4x4_final_3_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal Matrix_4x4_final_3_empty_n : STD_LOGIC;
    signal Matrix_4x4_final_3_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal Matrix_4x4_final_3_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal Matrix_4x4_final_4_full_n : STD_LOGIC;
    signal Matrix_4x4_final_4_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal Matrix_4x4_final_4_empty_n : STD_LOGIC;
    signal Matrix_4x4_final_4_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal Matrix_4x4_final_4_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal Matrix_4x4_final_5_full_n : STD_LOGIC;
    signal Matrix_4x4_final_5_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal Matrix_4x4_final_5_empty_n : STD_LOGIC;
    signal Matrix_4x4_final_5_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal Matrix_4x4_final_5_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal Matrix_4x4_final_6_full_n : STD_LOGIC;
    signal Matrix_4x4_final_6_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal Matrix_4x4_final_6_empty_n : STD_LOGIC;
    signal Matrix_4x4_final_6_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal Matrix_4x4_final_6_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal Matrix_4x4_final_7_full_n : STD_LOGIC;
    signal Matrix_4x4_final_7_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal Matrix_4x4_final_7_empty_n : STD_LOGIC;
    signal Matrix_4x4_final_7_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal Matrix_4x4_final_7_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal Matrix_4x4_final_8_full_n : STD_LOGIC;
    signal Matrix_4x4_final_8_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal Matrix_4x4_final_8_empty_n : STD_LOGIC;
    signal Matrix_4x4_final_8_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal Matrix_4x4_final_8_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal Matrix_4x4_final_9_full_n : STD_LOGIC;
    signal Matrix_4x4_final_9_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal Matrix_4x4_final_9_empty_n : STD_LOGIC;
    signal Matrix_4x4_final_9_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal Matrix_4x4_final_9_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal Matrix_4x4_final_10_full_n : STD_LOGIC;
    signal Matrix_4x4_final_10_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal Matrix_4x4_final_10_empty_n : STD_LOGIC;
    signal Matrix_4x4_final_10_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal Matrix_4x4_final_10_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal Matrix_4x4_final_11_full_n : STD_LOGIC;
    signal Matrix_4x4_final_11_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal Matrix_4x4_final_11_empty_n : STD_LOGIC;
    signal Matrix_4x4_final_11_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal Matrix_4x4_final_11_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal Matrix_4x4_final_12_full_n : STD_LOGIC;
    signal Matrix_4x4_final_12_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal Matrix_4x4_final_12_empty_n : STD_LOGIC;
    signal Matrix_4x4_final_12_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal Matrix_4x4_final_12_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal Matrix_4x4_final_13_full_n : STD_LOGIC;
    signal Matrix_4x4_final_13_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal Matrix_4x4_final_13_empty_n : STD_LOGIC;
    signal Matrix_4x4_final_13_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal Matrix_4x4_final_13_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal Matrix_4x4_final_14_full_n : STD_LOGIC;
    signal Matrix_4x4_final_14_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal Matrix_4x4_final_14_empty_n : STD_LOGIC;
    signal Matrix_4x4_final_14_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal Matrix_4x4_final_14_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal Matrix_4x4_final15_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal Matrix_4x4_final15_empty_n : STD_LOGIC;
    signal Matrix_4x4_final15_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal Matrix_4x4_final15_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component MatrixMult_NoCache_dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        size : IN STD_LOGIC_VECTOR (15 downto 0);
        m_axi_matrix_a_0_AWVALID : OUT STD_LOGIC;
        m_axi_matrix_a_0_AWREADY : IN STD_LOGIC;
        m_axi_matrix_a_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_matrix_a_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_a_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_matrix_a_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_matrix_a_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_a_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_a_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_matrix_a_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_matrix_a_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_matrix_a_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_matrix_a_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_a_0_WVALID : OUT STD_LOGIC;
        m_axi_matrix_a_0_WREADY : IN STD_LOGIC;
        m_axi_matrix_a_0_WDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
        m_axi_matrix_a_0_WSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_a_0_WLAST : OUT STD_LOGIC;
        m_axi_matrix_a_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_a_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_a_0_ARVALID : OUT STD_LOGIC;
        m_axi_matrix_a_0_ARREADY : IN STD_LOGIC;
        m_axi_matrix_a_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_matrix_a_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_a_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_matrix_a_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_matrix_a_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_a_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_a_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_matrix_a_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_matrix_a_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_matrix_a_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_matrix_a_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_a_0_RVALID : IN STD_LOGIC;
        m_axi_matrix_a_0_RREADY : OUT STD_LOGIC;
        m_axi_matrix_a_0_RDATA : IN STD_LOGIC_VECTOR (15 downto 0);
        m_axi_matrix_a_0_RLAST : IN STD_LOGIC;
        m_axi_matrix_a_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_a_0_RFIFONUM : IN STD_LOGIC_VECTOR (12 downto 0);
        m_axi_matrix_a_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_a_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_a_0_BVALID : IN STD_LOGIC;
        m_axi_matrix_a_0_BREADY : OUT STD_LOGIC;
        m_axi_matrix_a_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_a_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_a_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        matrix_in_1 : IN STD_LOGIC_VECTOR (63 downto 0);
        m_axi_matrix_b_0_AWVALID : OUT STD_LOGIC;
        m_axi_matrix_b_0_AWREADY : IN STD_LOGIC;
        m_axi_matrix_b_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_matrix_b_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_b_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_matrix_b_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_matrix_b_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_b_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_b_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_matrix_b_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_matrix_b_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_matrix_b_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_matrix_b_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_b_0_WVALID : OUT STD_LOGIC;
        m_axi_matrix_b_0_WREADY : IN STD_LOGIC;
        m_axi_matrix_b_0_WDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
        m_axi_matrix_b_0_WSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_b_0_WLAST : OUT STD_LOGIC;
        m_axi_matrix_b_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_b_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_b_0_ARVALID : OUT STD_LOGIC;
        m_axi_matrix_b_0_ARREADY : IN STD_LOGIC;
        m_axi_matrix_b_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_matrix_b_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_b_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_matrix_b_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_matrix_b_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_b_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_b_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_matrix_b_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_matrix_b_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_matrix_b_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_matrix_b_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_b_0_RVALID : IN STD_LOGIC;
        m_axi_matrix_b_0_RREADY : OUT STD_LOGIC;
        m_axi_matrix_b_0_RDATA : IN STD_LOGIC_VECTOR (15 downto 0);
        m_axi_matrix_b_0_RLAST : IN STD_LOGIC;
        m_axi_matrix_b_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_b_0_RFIFONUM : IN STD_LOGIC_VECTOR (12 downto 0);
        m_axi_matrix_b_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_b_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_b_0_BVALID : IN STD_LOGIC;
        m_axi_matrix_b_0_BREADY : OUT STD_LOGIC;
        m_axi_matrix_b_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_b_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_b_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        matrix_in_2 : IN STD_LOGIC_VECTOR (63 downto 0);
        p_read : IN STD_LOGIC_VECTOR (0 downto 0);
        p_read2 : IN STD_LOGIC_VECTOR (0 downto 0);
        p_read6 : IN STD_LOGIC_VECTOR (0 downto 0);
        p_read10 : IN STD_LOGIC_VECTOR (0 downto 0);
        p_read14 : IN STD_LOGIC_VECTOR (0 downto 0);
        p_read18 : IN STD_LOGIC_VECTOR (0 downto 0);
        p_read22 : IN STD_LOGIC_VECTOR (0 downto 0);
        p_read26 : IN STD_LOGIC_VECTOR (0 downto 0);
        p_read30 : IN STD_LOGIC_VECTOR (0 downto 0);
        p_read34 : IN STD_LOGIC_VECTOR (0 downto 0);
        p_read38 : IN STD_LOGIC_VECTOR (0 downto 0);
        p_read42 : IN STD_LOGIC_VECTOR (0 downto 0);
        p_read46 : IN STD_LOGIC_VECTOR (0 downto 0);
        p_read50 : IN STD_LOGIC_VECTOR (0 downto 0);
        p_read54 : IN STD_LOGIC_VECTOR (0 downto 0);
        p_read58 : IN STD_LOGIC_VECTOR (0 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_8 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_9 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_10 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_11 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_12 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_13 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_14 : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_return_15 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component MatrixMult_NoCache_matrixStitcher11 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_matrix_c_0_AWVALID : OUT STD_LOGIC;
        m_axi_matrix_c_0_AWREADY : IN STD_LOGIC;
        m_axi_matrix_c_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_matrix_c_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_c_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_matrix_c_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_matrix_c_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_c_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_c_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_matrix_c_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_matrix_c_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_matrix_c_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_matrix_c_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_c_0_WVALID : OUT STD_LOGIC;
        m_axi_matrix_c_0_WREADY : IN STD_LOGIC;
        m_axi_matrix_c_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_matrix_c_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_matrix_c_0_WLAST : OUT STD_LOGIC;
        m_axi_matrix_c_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_c_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_c_0_ARVALID : OUT STD_LOGIC;
        m_axi_matrix_c_0_ARREADY : IN STD_LOGIC;
        m_axi_matrix_c_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_matrix_c_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_c_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_matrix_c_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_matrix_c_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_c_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_c_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_matrix_c_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_matrix_c_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_matrix_c_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_matrix_c_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_c_0_RVALID : IN STD_LOGIC;
        m_axi_matrix_c_0_RREADY : OUT STD_LOGIC;
        m_axi_matrix_c_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_matrix_c_0_RLAST : IN STD_LOGIC;
        m_axi_matrix_c_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_c_0_RFIFONUM : IN STD_LOGIC_VECTOR (11 downto 0);
        m_axi_matrix_c_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_c_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_c_0_BVALID : IN STD_LOGIC;
        m_axi_matrix_c_0_BREADY : OUT STD_LOGIC;
        m_axi_matrix_c_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_c_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_c_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        ap_ce : IN STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read1 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read2 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read3 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read4 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read5 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read6 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read7 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read8 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read9 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read10 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read11 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read12 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read13 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read14 : IN STD_LOGIC_VECTOR (31 downto 0);
        p_read15 : IN STD_LOGIC_VECTOR (31 downto 0);
        size : IN STD_LOGIC_VECTOR (15 downto 0);
        matrix_out : IN STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component MatrixMult_NoCache_fifo_w32_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;



begin
    dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0 : component MatrixMult_NoCache_dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_start,
        ap_done => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_done,
        ap_continue => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_continue,
        ap_idle => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_idle,
        ap_ready => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_ready,
        size => size,
        m_axi_matrix_a_0_AWVALID => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWVALID,
        m_axi_matrix_a_0_AWREADY => ap_const_logic_0,
        m_axi_matrix_a_0_AWADDR => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWADDR,
        m_axi_matrix_a_0_AWID => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWID,
        m_axi_matrix_a_0_AWLEN => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWLEN,
        m_axi_matrix_a_0_AWSIZE => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWSIZE,
        m_axi_matrix_a_0_AWBURST => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWBURST,
        m_axi_matrix_a_0_AWLOCK => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWLOCK,
        m_axi_matrix_a_0_AWCACHE => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWCACHE,
        m_axi_matrix_a_0_AWPROT => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWPROT,
        m_axi_matrix_a_0_AWQOS => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWQOS,
        m_axi_matrix_a_0_AWREGION => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWREGION,
        m_axi_matrix_a_0_AWUSER => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_AWUSER,
        m_axi_matrix_a_0_WVALID => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_WVALID,
        m_axi_matrix_a_0_WREADY => ap_const_logic_0,
        m_axi_matrix_a_0_WDATA => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_WDATA,
        m_axi_matrix_a_0_WSTRB => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_WSTRB,
        m_axi_matrix_a_0_WLAST => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_WLAST,
        m_axi_matrix_a_0_WID => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_WID,
        m_axi_matrix_a_0_WUSER => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_WUSER,
        m_axi_matrix_a_0_ARVALID => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARVALID,
        m_axi_matrix_a_0_ARREADY => m_axi_matrix_a_0_ARREADY,
        m_axi_matrix_a_0_ARADDR => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARADDR,
        m_axi_matrix_a_0_ARID => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARID,
        m_axi_matrix_a_0_ARLEN => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARLEN,
        m_axi_matrix_a_0_ARSIZE => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARSIZE,
        m_axi_matrix_a_0_ARBURST => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARBURST,
        m_axi_matrix_a_0_ARLOCK => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARLOCK,
        m_axi_matrix_a_0_ARCACHE => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARCACHE,
        m_axi_matrix_a_0_ARPROT => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARPROT,
        m_axi_matrix_a_0_ARQOS => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARQOS,
        m_axi_matrix_a_0_ARREGION => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARREGION,
        m_axi_matrix_a_0_ARUSER => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARUSER,
        m_axi_matrix_a_0_RVALID => m_axi_matrix_a_0_RVALID,
        m_axi_matrix_a_0_RREADY => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_RREADY,
        m_axi_matrix_a_0_RDATA => m_axi_matrix_a_0_RDATA,
        m_axi_matrix_a_0_RLAST => m_axi_matrix_a_0_RLAST,
        m_axi_matrix_a_0_RID => m_axi_matrix_a_0_RID,
        m_axi_matrix_a_0_RFIFONUM => m_axi_matrix_a_0_RFIFONUM,
        m_axi_matrix_a_0_RUSER => m_axi_matrix_a_0_RUSER,
        m_axi_matrix_a_0_RRESP => m_axi_matrix_a_0_RRESP,
        m_axi_matrix_a_0_BVALID => ap_const_logic_0,
        m_axi_matrix_a_0_BREADY => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_BREADY,
        m_axi_matrix_a_0_BRESP => ap_const_lv2_0,
        m_axi_matrix_a_0_BID => ap_const_lv1_0,
        m_axi_matrix_a_0_BUSER => ap_const_lv1_0,
        matrix_in_1 => matrix_in_1,
        m_axi_matrix_b_0_AWVALID => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWVALID,
        m_axi_matrix_b_0_AWREADY => ap_const_logic_0,
        m_axi_matrix_b_0_AWADDR => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWADDR,
        m_axi_matrix_b_0_AWID => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWID,
        m_axi_matrix_b_0_AWLEN => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWLEN,
        m_axi_matrix_b_0_AWSIZE => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWSIZE,
        m_axi_matrix_b_0_AWBURST => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWBURST,
        m_axi_matrix_b_0_AWLOCK => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWLOCK,
        m_axi_matrix_b_0_AWCACHE => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWCACHE,
        m_axi_matrix_b_0_AWPROT => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWPROT,
        m_axi_matrix_b_0_AWQOS => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWQOS,
        m_axi_matrix_b_0_AWREGION => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWREGION,
        m_axi_matrix_b_0_AWUSER => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_AWUSER,
        m_axi_matrix_b_0_WVALID => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_WVALID,
        m_axi_matrix_b_0_WREADY => ap_const_logic_0,
        m_axi_matrix_b_0_WDATA => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_WDATA,
        m_axi_matrix_b_0_WSTRB => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_WSTRB,
        m_axi_matrix_b_0_WLAST => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_WLAST,
        m_axi_matrix_b_0_WID => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_WID,
        m_axi_matrix_b_0_WUSER => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_WUSER,
        m_axi_matrix_b_0_ARVALID => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARVALID,
        m_axi_matrix_b_0_ARREADY => m_axi_matrix_b_0_ARREADY,
        m_axi_matrix_b_0_ARADDR => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARADDR,
        m_axi_matrix_b_0_ARID => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARID,
        m_axi_matrix_b_0_ARLEN => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARLEN,
        m_axi_matrix_b_0_ARSIZE => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARSIZE,
        m_axi_matrix_b_0_ARBURST => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARBURST,
        m_axi_matrix_b_0_ARLOCK => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARLOCK,
        m_axi_matrix_b_0_ARCACHE => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARCACHE,
        m_axi_matrix_b_0_ARPROT => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARPROT,
        m_axi_matrix_b_0_ARQOS => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARQOS,
        m_axi_matrix_b_0_ARREGION => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARREGION,
        m_axi_matrix_b_0_ARUSER => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARUSER,
        m_axi_matrix_b_0_RVALID => m_axi_matrix_b_0_RVALID,
        m_axi_matrix_b_0_RREADY => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_RREADY,
        m_axi_matrix_b_0_RDATA => m_axi_matrix_b_0_RDATA,
        m_axi_matrix_b_0_RLAST => m_axi_matrix_b_0_RLAST,
        m_axi_matrix_b_0_RID => m_axi_matrix_b_0_RID,
        m_axi_matrix_b_0_RFIFONUM => m_axi_matrix_b_0_RFIFONUM,
        m_axi_matrix_b_0_RUSER => m_axi_matrix_b_0_RUSER,
        m_axi_matrix_b_0_RRESP => m_axi_matrix_b_0_RRESP,
        m_axi_matrix_b_0_BVALID => ap_const_logic_0,
        m_axi_matrix_b_0_BREADY => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_BREADY,
        m_axi_matrix_b_0_BRESP => ap_const_lv2_0,
        m_axi_matrix_b_0_BID => ap_const_lv1_0,
        m_axi_matrix_b_0_BUSER => ap_const_lv1_0,
        matrix_in_2 => matrix_in_2,
        p_read => ap_const_lv1_0,
        p_read2 => ap_const_lv1_0,
        p_read6 => ap_const_lv1_0,
        p_read10 => ap_const_lv1_0,
        p_read14 => ap_const_lv1_0,
        p_read18 => ap_const_lv1_0,
        p_read22 => ap_const_lv1_0,
        p_read26 => ap_const_lv1_0,
        p_read30 => ap_const_lv1_0,
        p_read34 => ap_const_lv1_0,
        p_read38 => ap_const_lv1_0,
        p_read42 => ap_const_lv1_0,
        p_read46 => ap_const_lv1_0,
        p_read50 => ap_const_lv1_0,
        p_read54 => ap_const_lv1_0,
        p_read58 => ap_const_lv1_0,
        ap_return_0 => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_0,
        ap_return_1 => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_1,
        ap_return_2 => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_2,
        ap_return_3 => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_3,
        ap_return_4 => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_4,
        ap_return_5 => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_5,
        ap_return_6 => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_6,
        ap_return_7 => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_7,
        ap_return_8 => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_8,
        ap_return_9 => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_9,
        ap_return_10 => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_10,
        ap_return_11 => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_11,
        ap_return_12 => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_12,
        ap_return_13 => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_13,
        ap_return_14 => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_14,
        ap_return_15 => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_15);

    matrixStitcher11_U0 : component MatrixMult_NoCache_matrixStitcher11
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => matrixStitcher11_U0_ap_start,
        ap_done => matrixStitcher11_U0_ap_done,
        ap_continue => matrixStitcher11_U0_ap_continue,
        ap_idle => matrixStitcher11_U0_ap_idle,
        ap_ready => matrixStitcher11_U0_ap_ready,
        m_axi_matrix_c_0_AWVALID => matrixStitcher11_U0_m_axi_matrix_c_0_AWVALID,
        m_axi_matrix_c_0_AWREADY => m_axi_matrix_c_0_AWREADY,
        m_axi_matrix_c_0_AWADDR => matrixStitcher11_U0_m_axi_matrix_c_0_AWADDR,
        m_axi_matrix_c_0_AWID => matrixStitcher11_U0_m_axi_matrix_c_0_AWID,
        m_axi_matrix_c_0_AWLEN => matrixStitcher11_U0_m_axi_matrix_c_0_AWLEN,
        m_axi_matrix_c_0_AWSIZE => matrixStitcher11_U0_m_axi_matrix_c_0_AWSIZE,
        m_axi_matrix_c_0_AWBURST => matrixStitcher11_U0_m_axi_matrix_c_0_AWBURST,
        m_axi_matrix_c_0_AWLOCK => matrixStitcher11_U0_m_axi_matrix_c_0_AWLOCK,
        m_axi_matrix_c_0_AWCACHE => matrixStitcher11_U0_m_axi_matrix_c_0_AWCACHE,
        m_axi_matrix_c_0_AWPROT => matrixStitcher11_U0_m_axi_matrix_c_0_AWPROT,
        m_axi_matrix_c_0_AWQOS => matrixStitcher11_U0_m_axi_matrix_c_0_AWQOS,
        m_axi_matrix_c_0_AWREGION => matrixStitcher11_U0_m_axi_matrix_c_0_AWREGION,
        m_axi_matrix_c_0_AWUSER => matrixStitcher11_U0_m_axi_matrix_c_0_AWUSER,
        m_axi_matrix_c_0_WVALID => matrixStitcher11_U0_m_axi_matrix_c_0_WVALID,
        m_axi_matrix_c_0_WREADY => m_axi_matrix_c_0_WREADY,
        m_axi_matrix_c_0_WDATA => matrixStitcher11_U0_m_axi_matrix_c_0_WDATA,
        m_axi_matrix_c_0_WSTRB => matrixStitcher11_U0_m_axi_matrix_c_0_WSTRB,
        m_axi_matrix_c_0_WLAST => matrixStitcher11_U0_m_axi_matrix_c_0_WLAST,
        m_axi_matrix_c_0_WID => matrixStitcher11_U0_m_axi_matrix_c_0_WID,
        m_axi_matrix_c_0_WUSER => matrixStitcher11_U0_m_axi_matrix_c_0_WUSER,
        m_axi_matrix_c_0_ARVALID => matrixStitcher11_U0_m_axi_matrix_c_0_ARVALID,
        m_axi_matrix_c_0_ARREADY => ap_const_logic_0,
        m_axi_matrix_c_0_ARADDR => matrixStitcher11_U0_m_axi_matrix_c_0_ARADDR,
        m_axi_matrix_c_0_ARID => matrixStitcher11_U0_m_axi_matrix_c_0_ARID,
        m_axi_matrix_c_0_ARLEN => matrixStitcher11_U0_m_axi_matrix_c_0_ARLEN,
        m_axi_matrix_c_0_ARSIZE => matrixStitcher11_U0_m_axi_matrix_c_0_ARSIZE,
        m_axi_matrix_c_0_ARBURST => matrixStitcher11_U0_m_axi_matrix_c_0_ARBURST,
        m_axi_matrix_c_0_ARLOCK => matrixStitcher11_U0_m_axi_matrix_c_0_ARLOCK,
        m_axi_matrix_c_0_ARCACHE => matrixStitcher11_U0_m_axi_matrix_c_0_ARCACHE,
        m_axi_matrix_c_0_ARPROT => matrixStitcher11_U0_m_axi_matrix_c_0_ARPROT,
        m_axi_matrix_c_0_ARQOS => matrixStitcher11_U0_m_axi_matrix_c_0_ARQOS,
        m_axi_matrix_c_0_ARREGION => matrixStitcher11_U0_m_axi_matrix_c_0_ARREGION,
        m_axi_matrix_c_0_ARUSER => matrixStitcher11_U0_m_axi_matrix_c_0_ARUSER,
        m_axi_matrix_c_0_RVALID => ap_const_logic_0,
        m_axi_matrix_c_0_RREADY => matrixStitcher11_U0_m_axi_matrix_c_0_RREADY,
        m_axi_matrix_c_0_RDATA => ap_const_lv32_0,
        m_axi_matrix_c_0_RLAST => ap_const_logic_0,
        m_axi_matrix_c_0_RID => ap_const_lv1_0,
        m_axi_matrix_c_0_RFIFONUM => ap_const_lv12_0,
        m_axi_matrix_c_0_RUSER => ap_const_lv1_0,
        m_axi_matrix_c_0_RRESP => ap_const_lv2_0,
        m_axi_matrix_c_0_BVALID => m_axi_matrix_c_0_BVALID,
        m_axi_matrix_c_0_BREADY => matrixStitcher11_U0_m_axi_matrix_c_0_BREADY,
        m_axi_matrix_c_0_BRESP => m_axi_matrix_c_0_BRESP,
        m_axi_matrix_c_0_BID => m_axi_matrix_c_0_BID,
        m_axi_matrix_c_0_BUSER => m_axi_matrix_c_0_BUSER,
        ap_ce => ap_const_logic_1,
        p_read => Matrix_4x4_final_dout,
        p_read1 => Matrix_4x4_final_1_dout,
        p_read2 => Matrix_4x4_final_2_dout,
        p_read3 => Matrix_4x4_final_3_dout,
        p_read4 => Matrix_4x4_final_4_dout,
        p_read5 => Matrix_4x4_final_5_dout,
        p_read6 => Matrix_4x4_final_6_dout,
        p_read7 => Matrix_4x4_final_7_dout,
        p_read8 => Matrix_4x4_final_8_dout,
        p_read9 => Matrix_4x4_final_9_dout,
        p_read10 => Matrix_4x4_final_10_dout,
        p_read11 => Matrix_4x4_final_11_dout,
        p_read12 => Matrix_4x4_final_12_dout,
        p_read13 => Matrix_4x4_final_13_dout,
        p_read14 => Matrix_4x4_final_14_dout,
        p_read15 => Matrix_4x4_final15_dout,
        size => size,
        matrix_out => matrix_out);

    Matrix_4x4_final_U : component MatrixMult_NoCache_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_0,
        if_full_n => Matrix_4x4_final_full_n,
        if_write => ap_channel_done_Matrix_4x4_final15,
        if_dout => Matrix_4x4_final_dout,
        if_empty_n => Matrix_4x4_final_empty_n,
        if_read => matrixStitcher11_U0_ap_ready,
        if_num_data_valid => Matrix_4x4_final_num_data_valid,
        if_fifo_cap => Matrix_4x4_final_fifo_cap);

    Matrix_4x4_final_1_U : component MatrixMult_NoCache_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_1,
        if_full_n => Matrix_4x4_final_1_full_n,
        if_write => ap_channel_done_Matrix_4x4_final15,
        if_dout => Matrix_4x4_final_1_dout,
        if_empty_n => Matrix_4x4_final_1_empty_n,
        if_read => matrixStitcher11_U0_ap_ready,
        if_num_data_valid => Matrix_4x4_final_1_num_data_valid,
        if_fifo_cap => Matrix_4x4_final_1_fifo_cap);

    Matrix_4x4_final_2_U : component MatrixMult_NoCache_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_2,
        if_full_n => Matrix_4x4_final_2_full_n,
        if_write => ap_channel_done_Matrix_4x4_final15,
        if_dout => Matrix_4x4_final_2_dout,
        if_empty_n => Matrix_4x4_final_2_empty_n,
        if_read => matrixStitcher11_U0_ap_ready,
        if_num_data_valid => Matrix_4x4_final_2_num_data_valid,
        if_fifo_cap => Matrix_4x4_final_2_fifo_cap);

    Matrix_4x4_final_3_U : component MatrixMult_NoCache_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_3,
        if_full_n => Matrix_4x4_final_3_full_n,
        if_write => ap_channel_done_Matrix_4x4_final15,
        if_dout => Matrix_4x4_final_3_dout,
        if_empty_n => Matrix_4x4_final_3_empty_n,
        if_read => matrixStitcher11_U0_ap_ready,
        if_num_data_valid => Matrix_4x4_final_3_num_data_valid,
        if_fifo_cap => Matrix_4x4_final_3_fifo_cap);

    Matrix_4x4_final_4_U : component MatrixMult_NoCache_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_4,
        if_full_n => Matrix_4x4_final_4_full_n,
        if_write => ap_channel_done_Matrix_4x4_final15,
        if_dout => Matrix_4x4_final_4_dout,
        if_empty_n => Matrix_4x4_final_4_empty_n,
        if_read => matrixStitcher11_U0_ap_ready,
        if_num_data_valid => Matrix_4x4_final_4_num_data_valid,
        if_fifo_cap => Matrix_4x4_final_4_fifo_cap);

    Matrix_4x4_final_5_U : component MatrixMult_NoCache_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_5,
        if_full_n => Matrix_4x4_final_5_full_n,
        if_write => ap_channel_done_Matrix_4x4_final15,
        if_dout => Matrix_4x4_final_5_dout,
        if_empty_n => Matrix_4x4_final_5_empty_n,
        if_read => matrixStitcher11_U0_ap_ready,
        if_num_data_valid => Matrix_4x4_final_5_num_data_valid,
        if_fifo_cap => Matrix_4x4_final_5_fifo_cap);

    Matrix_4x4_final_6_U : component MatrixMult_NoCache_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_6,
        if_full_n => Matrix_4x4_final_6_full_n,
        if_write => ap_channel_done_Matrix_4x4_final15,
        if_dout => Matrix_4x4_final_6_dout,
        if_empty_n => Matrix_4x4_final_6_empty_n,
        if_read => matrixStitcher11_U0_ap_ready,
        if_num_data_valid => Matrix_4x4_final_6_num_data_valid,
        if_fifo_cap => Matrix_4x4_final_6_fifo_cap);

    Matrix_4x4_final_7_U : component MatrixMult_NoCache_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_7,
        if_full_n => Matrix_4x4_final_7_full_n,
        if_write => ap_channel_done_Matrix_4x4_final15,
        if_dout => Matrix_4x4_final_7_dout,
        if_empty_n => Matrix_4x4_final_7_empty_n,
        if_read => matrixStitcher11_U0_ap_ready,
        if_num_data_valid => Matrix_4x4_final_7_num_data_valid,
        if_fifo_cap => Matrix_4x4_final_7_fifo_cap);

    Matrix_4x4_final_8_U : component MatrixMult_NoCache_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_8,
        if_full_n => Matrix_4x4_final_8_full_n,
        if_write => ap_channel_done_Matrix_4x4_final15,
        if_dout => Matrix_4x4_final_8_dout,
        if_empty_n => Matrix_4x4_final_8_empty_n,
        if_read => matrixStitcher11_U0_ap_ready,
        if_num_data_valid => Matrix_4x4_final_8_num_data_valid,
        if_fifo_cap => Matrix_4x4_final_8_fifo_cap);

    Matrix_4x4_final_9_U : component MatrixMult_NoCache_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_9,
        if_full_n => Matrix_4x4_final_9_full_n,
        if_write => ap_channel_done_Matrix_4x4_final15,
        if_dout => Matrix_4x4_final_9_dout,
        if_empty_n => Matrix_4x4_final_9_empty_n,
        if_read => matrixStitcher11_U0_ap_ready,
        if_num_data_valid => Matrix_4x4_final_9_num_data_valid,
        if_fifo_cap => Matrix_4x4_final_9_fifo_cap);

    Matrix_4x4_final_10_U : component MatrixMult_NoCache_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_10,
        if_full_n => Matrix_4x4_final_10_full_n,
        if_write => ap_channel_done_Matrix_4x4_final15,
        if_dout => Matrix_4x4_final_10_dout,
        if_empty_n => Matrix_4x4_final_10_empty_n,
        if_read => matrixStitcher11_U0_ap_ready,
        if_num_data_valid => Matrix_4x4_final_10_num_data_valid,
        if_fifo_cap => Matrix_4x4_final_10_fifo_cap);

    Matrix_4x4_final_11_U : component MatrixMult_NoCache_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_11,
        if_full_n => Matrix_4x4_final_11_full_n,
        if_write => ap_channel_done_Matrix_4x4_final15,
        if_dout => Matrix_4x4_final_11_dout,
        if_empty_n => Matrix_4x4_final_11_empty_n,
        if_read => matrixStitcher11_U0_ap_ready,
        if_num_data_valid => Matrix_4x4_final_11_num_data_valid,
        if_fifo_cap => Matrix_4x4_final_11_fifo_cap);

    Matrix_4x4_final_12_U : component MatrixMult_NoCache_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_12,
        if_full_n => Matrix_4x4_final_12_full_n,
        if_write => ap_channel_done_Matrix_4x4_final15,
        if_dout => Matrix_4x4_final_12_dout,
        if_empty_n => Matrix_4x4_final_12_empty_n,
        if_read => matrixStitcher11_U0_ap_ready,
        if_num_data_valid => Matrix_4x4_final_12_num_data_valid,
        if_fifo_cap => Matrix_4x4_final_12_fifo_cap);

    Matrix_4x4_final_13_U : component MatrixMult_NoCache_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_13,
        if_full_n => Matrix_4x4_final_13_full_n,
        if_write => ap_channel_done_Matrix_4x4_final15,
        if_dout => Matrix_4x4_final_13_dout,
        if_empty_n => Matrix_4x4_final_13_empty_n,
        if_read => matrixStitcher11_U0_ap_ready,
        if_num_data_valid => Matrix_4x4_final_13_num_data_valid,
        if_fifo_cap => Matrix_4x4_final_13_fifo_cap);

    Matrix_4x4_final_14_U : component MatrixMult_NoCache_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_14,
        if_full_n => Matrix_4x4_final_14_full_n,
        if_write => ap_channel_done_Matrix_4x4_final15,
        if_dout => Matrix_4x4_final_14_dout,
        if_empty_n => Matrix_4x4_final_14_empty_n,
        if_read => matrixStitcher11_U0_ap_ready,
        if_num_data_valid => Matrix_4x4_final_14_num_data_valid,
        if_fifo_cap => Matrix_4x4_final_14_fifo_cap);

    Matrix_4x4_final15_U : component MatrixMult_NoCache_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_return_15,
        if_full_n => Matrix_4x4_final15_full_n,
        if_write => ap_channel_done_Matrix_4x4_final15,
        if_dout => Matrix_4x4_final15_dout,
        if_empty_n => Matrix_4x4_final15_empty_n,
        if_read => matrixStitcher11_U0_ap_ready,
        if_num_data_valid => Matrix_4x4_final15_num_data_valid,
        if_fifo_cap => Matrix_4x4_final15_fifo_cap);





    ap_sync_reg_channel_write_Matrix_4x4_final15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_channel_write_Matrix_4x4_final15 <= ap_const_logic_0;
            else
                if (((dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_done and dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_continue) = ap_const_logic_1)) then 
                    ap_sync_reg_channel_write_Matrix_4x4_final15 <= ap_const_logic_0;
                else 
                    ap_sync_reg_channel_write_Matrix_4x4_final15 <= ap_sync_channel_write_Matrix_4x4_final15;
                end if; 
            end if;
        end if;
    end process;

    ap_channel_done_Matrix_4x4_final15 <= ((ap_sync_reg_channel_write_Matrix_4x4_final15 xor ap_const_logic_1) and dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_done);
    ap_done <= matrixStitcher11_U0_ap_done;
    ap_idle <= (matrixStitcher11_U0_ap_idle and (ap_const_logic_1 xor Matrix_4x4_final_empty_n) and dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_idle);
    ap_ready <= dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_ready;
    ap_sync_channel_write_Matrix_4x4_final15 <= ((ap_channel_done_Matrix_4x4_final15 and Matrix_4x4_final15_full_n) or ap_sync_reg_channel_write_Matrix_4x4_final15);
    dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_continue <= ap_sync_channel_write_Matrix_4x4_final15;
    dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_ap_start <= ap_start;
    m_axi_matrix_a_0_ARADDR <= dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARADDR;
    m_axi_matrix_a_0_ARBURST <= dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARBURST;
    m_axi_matrix_a_0_ARCACHE <= dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARCACHE;
    m_axi_matrix_a_0_ARID <= dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARID;
    m_axi_matrix_a_0_ARLEN <= dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARLEN;
    m_axi_matrix_a_0_ARLOCK <= dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARLOCK;
    m_axi_matrix_a_0_ARPROT <= dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARPROT;
    m_axi_matrix_a_0_ARQOS <= dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARQOS;
    m_axi_matrix_a_0_ARREGION <= dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARREGION;
    m_axi_matrix_a_0_ARSIZE <= dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARSIZE;
    m_axi_matrix_a_0_ARUSER <= dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARUSER;
    m_axi_matrix_a_0_ARVALID <= dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_ARVALID;
    m_axi_matrix_a_0_AWADDR <= ap_const_lv64_0;
    m_axi_matrix_a_0_AWBURST <= ap_const_lv2_0;
    m_axi_matrix_a_0_AWCACHE <= ap_const_lv4_0;
    m_axi_matrix_a_0_AWID <= ap_const_lv1_0;
    m_axi_matrix_a_0_AWLEN <= ap_const_lv32_0;
    m_axi_matrix_a_0_AWLOCK <= ap_const_lv2_0;
    m_axi_matrix_a_0_AWPROT <= ap_const_lv3_0;
    m_axi_matrix_a_0_AWQOS <= ap_const_lv4_0;
    m_axi_matrix_a_0_AWREGION <= ap_const_lv4_0;
    m_axi_matrix_a_0_AWSIZE <= ap_const_lv3_0;
    m_axi_matrix_a_0_AWUSER <= ap_const_lv1_0;
    m_axi_matrix_a_0_AWVALID <= ap_const_logic_0;
    m_axi_matrix_a_0_BREADY <= ap_const_logic_0;
    m_axi_matrix_a_0_RREADY <= dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_a_0_RREADY;
    m_axi_matrix_a_0_WDATA <= ap_const_lv16_0;
    m_axi_matrix_a_0_WID <= ap_const_lv1_0;
    m_axi_matrix_a_0_WLAST <= ap_const_logic_0;
    m_axi_matrix_a_0_WSTRB <= ap_const_lv2_0;
    m_axi_matrix_a_0_WUSER <= ap_const_lv1_0;
    m_axi_matrix_a_0_WVALID <= ap_const_logic_0;
    m_axi_matrix_b_0_ARADDR <= dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARADDR;
    m_axi_matrix_b_0_ARBURST <= dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARBURST;
    m_axi_matrix_b_0_ARCACHE <= dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARCACHE;
    m_axi_matrix_b_0_ARID <= dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARID;
    m_axi_matrix_b_0_ARLEN <= dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARLEN;
    m_axi_matrix_b_0_ARLOCK <= dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARLOCK;
    m_axi_matrix_b_0_ARPROT <= dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARPROT;
    m_axi_matrix_b_0_ARQOS <= dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARQOS;
    m_axi_matrix_b_0_ARREGION <= dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARREGION;
    m_axi_matrix_b_0_ARSIZE <= dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARSIZE;
    m_axi_matrix_b_0_ARUSER <= dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARUSER;
    m_axi_matrix_b_0_ARVALID <= dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_ARVALID;
    m_axi_matrix_b_0_AWADDR <= ap_const_lv64_0;
    m_axi_matrix_b_0_AWBURST <= ap_const_lv2_0;
    m_axi_matrix_b_0_AWCACHE <= ap_const_lv4_0;
    m_axi_matrix_b_0_AWID <= ap_const_lv1_0;
    m_axi_matrix_b_0_AWLEN <= ap_const_lv32_0;
    m_axi_matrix_b_0_AWLOCK <= ap_const_lv2_0;
    m_axi_matrix_b_0_AWPROT <= ap_const_lv3_0;
    m_axi_matrix_b_0_AWQOS <= ap_const_lv4_0;
    m_axi_matrix_b_0_AWREGION <= ap_const_lv4_0;
    m_axi_matrix_b_0_AWSIZE <= ap_const_lv3_0;
    m_axi_matrix_b_0_AWUSER <= ap_const_lv1_0;
    m_axi_matrix_b_0_AWVALID <= ap_const_logic_0;
    m_axi_matrix_b_0_BREADY <= ap_const_logic_0;
    m_axi_matrix_b_0_RREADY <= dataflow_in_loop_VITIS_LOOP_24_1_1_Loop_VITIS_LOOP_30_2_proc10_U0_m_axi_matrix_b_0_RREADY;
    m_axi_matrix_b_0_WDATA <= ap_const_lv16_0;
    m_axi_matrix_b_0_WID <= ap_const_lv1_0;
    m_axi_matrix_b_0_WLAST <= ap_const_logic_0;
    m_axi_matrix_b_0_WSTRB <= ap_const_lv2_0;
    m_axi_matrix_b_0_WUSER <= ap_const_lv1_0;
    m_axi_matrix_b_0_WVALID <= ap_const_logic_0;
    m_axi_matrix_c_0_ARADDR <= ap_const_lv64_0;
    m_axi_matrix_c_0_ARBURST <= ap_const_lv2_0;
    m_axi_matrix_c_0_ARCACHE <= ap_const_lv4_0;
    m_axi_matrix_c_0_ARID <= ap_const_lv1_0;
    m_axi_matrix_c_0_ARLEN <= ap_const_lv32_0;
    m_axi_matrix_c_0_ARLOCK <= ap_const_lv2_0;
    m_axi_matrix_c_0_ARPROT <= ap_const_lv3_0;
    m_axi_matrix_c_0_ARQOS <= ap_const_lv4_0;
    m_axi_matrix_c_0_ARREGION <= ap_const_lv4_0;
    m_axi_matrix_c_0_ARSIZE <= ap_const_lv3_0;
    m_axi_matrix_c_0_ARUSER <= ap_const_lv1_0;
    m_axi_matrix_c_0_ARVALID <= ap_const_logic_0;
    m_axi_matrix_c_0_AWADDR <= matrixStitcher11_U0_m_axi_matrix_c_0_AWADDR;
    m_axi_matrix_c_0_AWBURST <= matrixStitcher11_U0_m_axi_matrix_c_0_AWBURST;
    m_axi_matrix_c_0_AWCACHE <= matrixStitcher11_U0_m_axi_matrix_c_0_AWCACHE;
    m_axi_matrix_c_0_AWID <= matrixStitcher11_U0_m_axi_matrix_c_0_AWID;
    m_axi_matrix_c_0_AWLEN <= matrixStitcher11_U0_m_axi_matrix_c_0_AWLEN;
    m_axi_matrix_c_0_AWLOCK <= matrixStitcher11_U0_m_axi_matrix_c_0_AWLOCK;
    m_axi_matrix_c_0_AWPROT <= matrixStitcher11_U0_m_axi_matrix_c_0_AWPROT;
    m_axi_matrix_c_0_AWQOS <= matrixStitcher11_U0_m_axi_matrix_c_0_AWQOS;
    m_axi_matrix_c_0_AWREGION <= matrixStitcher11_U0_m_axi_matrix_c_0_AWREGION;
    m_axi_matrix_c_0_AWSIZE <= matrixStitcher11_U0_m_axi_matrix_c_0_AWSIZE;
    m_axi_matrix_c_0_AWUSER <= matrixStitcher11_U0_m_axi_matrix_c_0_AWUSER;
    m_axi_matrix_c_0_AWVALID <= matrixStitcher11_U0_m_axi_matrix_c_0_AWVALID;
    m_axi_matrix_c_0_BREADY <= matrixStitcher11_U0_m_axi_matrix_c_0_BREADY;
    m_axi_matrix_c_0_RREADY <= ap_const_logic_0;
    m_axi_matrix_c_0_WDATA <= matrixStitcher11_U0_m_axi_matrix_c_0_WDATA;
    m_axi_matrix_c_0_WID <= matrixStitcher11_U0_m_axi_matrix_c_0_WID;
    m_axi_matrix_c_0_WLAST <= matrixStitcher11_U0_m_axi_matrix_c_0_WLAST;
    m_axi_matrix_c_0_WSTRB <= matrixStitcher11_U0_m_axi_matrix_c_0_WSTRB;
    m_axi_matrix_c_0_WUSER <= matrixStitcher11_U0_m_axi_matrix_c_0_WUSER;
    m_axi_matrix_c_0_WVALID <= matrixStitcher11_U0_m_axi_matrix_c_0_WVALID;
    matrixStitcher11_U0_ap_continue <= ap_continue;
    matrixStitcher11_U0_ap_start <= Matrix_4x4_final_empty_n;
end behav;
