-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity MatrixMult_dataflow_parent_loop_proc is
port (
    mul : IN STD_LOGIC_VECTOR (27 downto 0);
    size : IN STD_LOGIC_VECTOR (15 downto 0);
    m_axi_matrix_a_0_AWVALID : OUT STD_LOGIC;
    m_axi_matrix_a_0_AWREADY : IN STD_LOGIC;
    m_axi_matrix_a_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_matrix_a_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_a_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_matrix_a_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_matrix_a_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_a_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_a_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_matrix_a_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_matrix_a_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_matrix_a_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_matrix_a_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_a_0_WVALID : OUT STD_LOGIC;
    m_axi_matrix_a_0_WREADY : IN STD_LOGIC;
    m_axi_matrix_a_0_WDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    m_axi_matrix_a_0_WSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_a_0_WLAST : OUT STD_LOGIC;
    m_axi_matrix_a_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_a_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_a_0_ARVALID : OUT STD_LOGIC;
    m_axi_matrix_a_0_ARREADY : IN STD_LOGIC;
    m_axi_matrix_a_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_matrix_a_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_a_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_matrix_a_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_matrix_a_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_a_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_a_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_matrix_a_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_matrix_a_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_matrix_a_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_matrix_a_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_a_0_RVALID : IN STD_LOGIC;
    m_axi_matrix_a_0_RREADY : OUT STD_LOGIC;
    m_axi_matrix_a_0_RDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    m_axi_matrix_a_0_RLAST : IN STD_LOGIC;
    m_axi_matrix_a_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_a_0_RFIFONUM : IN STD_LOGIC_VECTOR (12 downto 0);
    m_axi_matrix_a_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_a_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_a_0_BVALID : IN STD_LOGIC;
    m_axi_matrix_a_0_BREADY : OUT STD_LOGIC;
    m_axi_matrix_a_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_a_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_a_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    matrix_in_1 : IN STD_LOGIC_VECTOR (63 downto 0);
    m_axi_matrix_b_0_AWVALID : OUT STD_LOGIC;
    m_axi_matrix_b_0_AWREADY : IN STD_LOGIC;
    m_axi_matrix_b_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_matrix_b_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_b_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_matrix_b_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_matrix_b_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_b_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_b_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_matrix_b_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_matrix_b_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_matrix_b_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_matrix_b_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_b_0_WVALID : OUT STD_LOGIC;
    m_axi_matrix_b_0_WREADY : IN STD_LOGIC;
    m_axi_matrix_b_0_WDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    m_axi_matrix_b_0_WSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_b_0_WLAST : OUT STD_LOGIC;
    m_axi_matrix_b_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_b_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_b_0_ARVALID : OUT STD_LOGIC;
    m_axi_matrix_b_0_ARREADY : IN STD_LOGIC;
    m_axi_matrix_b_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_matrix_b_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_b_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_matrix_b_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_matrix_b_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_b_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_b_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_matrix_b_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_matrix_b_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_matrix_b_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_matrix_b_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_b_0_RVALID : IN STD_LOGIC;
    m_axi_matrix_b_0_RREADY : OUT STD_LOGIC;
    m_axi_matrix_b_0_RDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    m_axi_matrix_b_0_RLAST : IN STD_LOGIC;
    m_axi_matrix_b_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_b_0_RFIFONUM : IN STD_LOGIC_VECTOR (12 downto 0);
    m_axi_matrix_b_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_b_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_b_0_BVALID : IN STD_LOGIC;
    m_axi_matrix_b_0_BREADY : OUT STD_LOGIC;
    m_axi_matrix_b_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_b_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_b_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    matrix_in_2 : IN STD_LOGIC_VECTOR (63 downto 0);
    m_axi_matrix_c_0_AWVALID : OUT STD_LOGIC;
    m_axi_matrix_c_0_AWREADY : IN STD_LOGIC;
    m_axi_matrix_c_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_matrix_c_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_c_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_matrix_c_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_matrix_c_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_c_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_c_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_matrix_c_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_matrix_c_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_matrix_c_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_matrix_c_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_c_0_WVALID : OUT STD_LOGIC;
    m_axi_matrix_c_0_WREADY : IN STD_LOGIC;
    m_axi_matrix_c_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_matrix_c_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_matrix_c_0_WLAST : OUT STD_LOGIC;
    m_axi_matrix_c_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_c_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_c_0_ARVALID : OUT STD_LOGIC;
    m_axi_matrix_c_0_ARREADY : IN STD_LOGIC;
    m_axi_matrix_c_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_matrix_c_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_c_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_matrix_c_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_matrix_c_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_c_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_c_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_matrix_c_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_matrix_c_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_matrix_c_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_matrix_c_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_c_0_RVALID : IN STD_LOGIC;
    m_axi_matrix_c_0_RREADY : OUT STD_LOGIC;
    m_axi_matrix_c_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_matrix_c_0_RLAST : IN STD_LOGIC;
    m_axi_matrix_c_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_c_0_RFIFONUM : IN STD_LOGIC_VECTOR (11 downto 0);
    m_axi_matrix_c_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_c_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_c_0_BVALID : IN STD_LOGIC;
    m_axi_matrix_c_0_BREADY : OUT STD_LOGIC;
    m_axi_matrix_c_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_matrix_c_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_matrix_c_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    matrix_out : IN STD_LOGIC_VECTOR (63 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    size_ap_vld : IN STD_LOGIC;
    matrix_in_1_ap_vld : IN STD_LOGIC;
    matrix_in_2_ap_vld : IN STD_LOGIC;
    matrix_out_ap_vld : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of MatrixMult_dataflow_parent_loop_proc is 
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv28_0 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000000000000";
    constant ap_const_lv28_1 : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000000000001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWVALID : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_WVALID : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_WDATA : STD_LOGIC_VECTOR (15 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_WSTRB : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_WLAST : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARVALID : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_RREADY : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_BREADY : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWVALID : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_WVALID : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_WDATA : STD_LOGIC_VECTOR (15 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_WSTRB : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_WLAST : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARVALID : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_RREADY : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_BREADY : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWVALID : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_WVALID : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_WLAST : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARVALID : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_RREADY : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_BREADY : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_start : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_done : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_ready : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_idle : STD_LOGIC;
    signal dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_continue : STD_LOGIC;
    signal loop_dataflow_input_count : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000000000000";
    signal loop_dataflow_output_count : STD_LOGIC_VECTOR (27 downto 0) := "0000000000000000000000000000";
    signal ap_input_count_plus_step : STD_LOGIC_VECTOR (27 downto 0);
    signal ap_output_count_plus_step : STD_LOGIC_VECTOR (27 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component MatrixMult_dataflow_in_loop_VITIS_LOOP_24_1_1 IS
    port (
        size : IN STD_LOGIC_VECTOR (15 downto 0);
        m_axi_matrix_a_0_AWVALID : OUT STD_LOGIC;
        m_axi_matrix_a_0_AWREADY : IN STD_LOGIC;
        m_axi_matrix_a_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_matrix_a_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_a_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_matrix_a_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_matrix_a_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_a_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_a_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_matrix_a_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_matrix_a_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_matrix_a_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_matrix_a_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_a_0_WVALID : OUT STD_LOGIC;
        m_axi_matrix_a_0_WREADY : IN STD_LOGIC;
        m_axi_matrix_a_0_WDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
        m_axi_matrix_a_0_WSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_a_0_WLAST : OUT STD_LOGIC;
        m_axi_matrix_a_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_a_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_a_0_ARVALID : OUT STD_LOGIC;
        m_axi_matrix_a_0_ARREADY : IN STD_LOGIC;
        m_axi_matrix_a_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_matrix_a_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_a_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_matrix_a_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_matrix_a_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_a_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_a_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_matrix_a_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_matrix_a_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_matrix_a_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_matrix_a_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_a_0_RVALID : IN STD_LOGIC;
        m_axi_matrix_a_0_RREADY : OUT STD_LOGIC;
        m_axi_matrix_a_0_RDATA : IN STD_LOGIC_VECTOR (15 downto 0);
        m_axi_matrix_a_0_RLAST : IN STD_LOGIC;
        m_axi_matrix_a_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_a_0_RFIFONUM : IN STD_LOGIC_VECTOR (12 downto 0);
        m_axi_matrix_a_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_a_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_a_0_BVALID : IN STD_LOGIC;
        m_axi_matrix_a_0_BREADY : OUT STD_LOGIC;
        m_axi_matrix_a_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_a_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_a_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        matrix_in_1 : IN STD_LOGIC_VECTOR (63 downto 0);
        m_axi_matrix_b_0_AWVALID : OUT STD_LOGIC;
        m_axi_matrix_b_0_AWREADY : IN STD_LOGIC;
        m_axi_matrix_b_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_matrix_b_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_b_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_matrix_b_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_matrix_b_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_b_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_b_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_matrix_b_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_matrix_b_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_matrix_b_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_matrix_b_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_b_0_WVALID : OUT STD_LOGIC;
        m_axi_matrix_b_0_WREADY : IN STD_LOGIC;
        m_axi_matrix_b_0_WDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
        m_axi_matrix_b_0_WSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_b_0_WLAST : OUT STD_LOGIC;
        m_axi_matrix_b_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_b_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_b_0_ARVALID : OUT STD_LOGIC;
        m_axi_matrix_b_0_ARREADY : IN STD_LOGIC;
        m_axi_matrix_b_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_matrix_b_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_b_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_matrix_b_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_matrix_b_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_b_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_b_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_matrix_b_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_matrix_b_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_matrix_b_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_matrix_b_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_b_0_RVALID : IN STD_LOGIC;
        m_axi_matrix_b_0_RREADY : OUT STD_LOGIC;
        m_axi_matrix_b_0_RDATA : IN STD_LOGIC_VECTOR (15 downto 0);
        m_axi_matrix_b_0_RLAST : IN STD_LOGIC;
        m_axi_matrix_b_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_b_0_RFIFONUM : IN STD_LOGIC_VECTOR (12 downto 0);
        m_axi_matrix_b_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_b_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_b_0_BVALID : IN STD_LOGIC;
        m_axi_matrix_b_0_BREADY : OUT STD_LOGIC;
        m_axi_matrix_b_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_b_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_b_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        matrix_in_2 : IN STD_LOGIC_VECTOR (63 downto 0);
        m_axi_matrix_c_0_AWVALID : OUT STD_LOGIC;
        m_axi_matrix_c_0_AWREADY : IN STD_LOGIC;
        m_axi_matrix_c_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_matrix_c_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_c_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_matrix_c_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_matrix_c_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_c_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_c_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_matrix_c_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_matrix_c_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_matrix_c_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_matrix_c_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_c_0_WVALID : OUT STD_LOGIC;
        m_axi_matrix_c_0_WREADY : IN STD_LOGIC;
        m_axi_matrix_c_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_matrix_c_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_matrix_c_0_WLAST : OUT STD_LOGIC;
        m_axi_matrix_c_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_c_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_c_0_ARVALID : OUT STD_LOGIC;
        m_axi_matrix_c_0_ARREADY : IN STD_LOGIC;
        m_axi_matrix_c_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_matrix_c_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_c_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_matrix_c_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_matrix_c_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_c_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_c_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_matrix_c_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_matrix_c_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_matrix_c_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_matrix_c_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_c_0_RVALID : IN STD_LOGIC;
        m_axi_matrix_c_0_RREADY : OUT STD_LOGIC;
        m_axi_matrix_c_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_matrix_c_0_RLAST : IN STD_LOGIC;
        m_axi_matrix_c_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_c_0_RFIFONUM : IN STD_LOGIC_VECTOR (11 downto 0);
        m_axi_matrix_c_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_c_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_c_0_BVALID : IN STD_LOGIC;
        m_axi_matrix_c_0_BREADY : OUT STD_LOGIC;
        m_axi_matrix_c_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_matrix_c_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_matrix_c_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        matrix_out : IN STD_LOGIC_VECTOR (63 downto 0);
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        size_ap_vld : IN STD_LOGIC;
        matrix_in_1_ap_vld : IN STD_LOGIC;
        matrix_in_2_ap_vld : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        matrix_out_ap_vld : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    dataflow_in_loop_VITIS_LOOP_24_1_1_U0 : component MatrixMult_dataflow_in_loop_VITIS_LOOP_24_1_1
    port map (
        size => size,
        m_axi_matrix_a_0_AWVALID => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWVALID,
        m_axi_matrix_a_0_AWREADY => ap_const_logic_0,
        m_axi_matrix_a_0_AWADDR => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWADDR,
        m_axi_matrix_a_0_AWID => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWID,
        m_axi_matrix_a_0_AWLEN => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWLEN,
        m_axi_matrix_a_0_AWSIZE => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWSIZE,
        m_axi_matrix_a_0_AWBURST => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWBURST,
        m_axi_matrix_a_0_AWLOCK => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWLOCK,
        m_axi_matrix_a_0_AWCACHE => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWCACHE,
        m_axi_matrix_a_0_AWPROT => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWPROT,
        m_axi_matrix_a_0_AWQOS => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWQOS,
        m_axi_matrix_a_0_AWREGION => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWREGION,
        m_axi_matrix_a_0_AWUSER => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_AWUSER,
        m_axi_matrix_a_0_WVALID => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_WVALID,
        m_axi_matrix_a_0_WREADY => ap_const_logic_0,
        m_axi_matrix_a_0_WDATA => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_WDATA,
        m_axi_matrix_a_0_WSTRB => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_WSTRB,
        m_axi_matrix_a_0_WLAST => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_WLAST,
        m_axi_matrix_a_0_WID => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_WID,
        m_axi_matrix_a_0_WUSER => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_WUSER,
        m_axi_matrix_a_0_ARVALID => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARVALID,
        m_axi_matrix_a_0_ARREADY => m_axi_matrix_a_0_ARREADY,
        m_axi_matrix_a_0_ARADDR => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARADDR,
        m_axi_matrix_a_0_ARID => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARID,
        m_axi_matrix_a_0_ARLEN => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARLEN,
        m_axi_matrix_a_0_ARSIZE => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARSIZE,
        m_axi_matrix_a_0_ARBURST => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARBURST,
        m_axi_matrix_a_0_ARLOCK => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARLOCK,
        m_axi_matrix_a_0_ARCACHE => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARCACHE,
        m_axi_matrix_a_0_ARPROT => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARPROT,
        m_axi_matrix_a_0_ARQOS => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARQOS,
        m_axi_matrix_a_0_ARREGION => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARREGION,
        m_axi_matrix_a_0_ARUSER => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARUSER,
        m_axi_matrix_a_0_RVALID => m_axi_matrix_a_0_RVALID,
        m_axi_matrix_a_0_RREADY => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_RREADY,
        m_axi_matrix_a_0_RDATA => m_axi_matrix_a_0_RDATA,
        m_axi_matrix_a_0_RLAST => m_axi_matrix_a_0_RLAST,
        m_axi_matrix_a_0_RID => m_axi_matrix_a_0_RID,
        m_axi_matrix_a_0_RFIFONUM => m_axi_matrix_a_0_RFIFONUM,
        m_axi_matrix_a_0_RUSER => m_axi_matrix_a_0_RUSER,
        m_axi_matrix_a_0_RRESP => m_axi_matrix_a_0_RRESP,
        m_axi_matrix_a_0_BVALID => ap_const_logic_0,
        m_axi_matrix_a_0_BREADY => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_BREADY,
        m_axi_matrix_a_0_BRESP => ap_const_lv2_0,
        m_axi_matrix_a_0_BID => ap_const_lv1_0,
        m_axi_matrix_a_0_BUSER => ap_const_lv1_0,
        matrix_in_1 => matrix_in_1,
        m_axi_matrix_b_0_AWVALID => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWVALID,
        m_axi_matrix_b_0_AWREADY => ap_const_logic_0,
        m_axi_matrix_b_0_AWADDR => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWADDR,
        m_axi_matrix_b_0_AWID => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWID,
        m_axi_matrix_b_0_AWLEN => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWLEN,
        m_axi_matrix_b_0_AWSIZE => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWSIZE,
        m_axi_matrix_b_0_AWBURST => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWBURST,
        m_axi_matrix_b_0_AWLOCK => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWLOCK,
        m_axi_matrix_b_0_AWCACHE => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWCACHE,
        m_axi_matrix_b_0_AWPROT => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWPROT,
        m_axi_matrix_b_0_AWQOS => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWQOS,
        m_axi_matrix_b_0_AWREGION => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWREGION,
        m_axi_matrix_b_0_AWUSER => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_AWUSER,
        m_axi_matrix_b_0_WVALID => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_WVALID,
        m_axi_matrix_b_0_WREADY => ap_const_logic_0,
        m_axi_matrix_b_0_WDATA => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_WDATA,
        m_axi_matrix_b_0_WSTRB => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_WSTRB,
        m_axi_matrix_b_0_WLAST => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_WLAST,
        m_axi_matrix_b_0_WID => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_WID,
        m_axi_matrix_b_0_WUSER => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_WUSER,
        m_axi_matrix_b_0_ARVALID => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARVALID,
        m_axi_matrix_b_0_ARREADY => m_axi_matrix_b_0_ARREADY,
        m_axi_matrix_b_0_ARADDR => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARADDR,
        m_axi_matrix_b_0_ARID => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARID,
        m_axi_matrix_b_0_ARLEN => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARLEN,
        m_axi_matrix_b_0_ARSIZE => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARSIZE,
        m_axi_matrix_b_0_ARBURST => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARBURST,
        m_axi_matrix_b_0_ARLOCK => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARLOCK,
        m_axi_matrix_b_0_ARCACHE => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARCACHE,
        m_axi_matrix_b_0_ARPROT => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARPROT,
        m_axi_matrix_b_0_ARQOS => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARQOS,
        m_axi_matrix_b_0_ARREGION => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARREGION,
        m_axi_matrix_b_0_ARUSER => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARUSER,
        m_axi_matrix_b_0_RVALID => m_axi_matrix_b_0_RVALID,
        m_axi_matrix_b_0_RREADY => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_RREADY,
        m_axi_matrix_b_0_RDATA => m_axi_matrix_b_0_RDATA,
        m_axi_matrix_b_0_RLAST => m_axi_matrix_b_0_RLAST,
        m_axi_matrix_b_0_RID => m_axi_matrix_b_0_RID,
        m_axi_matrix_b_0_RFIFONUM => m_axi_matrix_b_0_RFIFONUM,
        m_axi_matrix_b_0_RUSER => m_axi_matrix_b_0_RUSER,
        m_axi_matrix_b_0_RRESP => m_axi_matrix_b_0_RRESP,
        m_axi_matrix_b_0_BVALID => ap_const_logic_0,
        m_axi_matrix_b_0_BREADY => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_BREADY,
        m_axi_matrix_b_0_BRESP => ap_const_lv2_0,
        m_axi_matrix_b_0_BID => ap_const_lv1_0,
        m_axi_matrix_b_0_BUSER => ap_const_lv1_0,
        matrix_in_2 => matrix_in_2,
        m_axi_matrix_c_0_AWVALID => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWVALID,
        m_axi_matrix_c_0_AWREADY => m_axi_matrix_c_0_AWREADY,
        m_axi_matrix_c_0_AWADDR => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWADDR,
        m_axi_matrix_c_0_AWID => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWID,
        m_axi_matrix_c_0_AWLEN => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWLEN,
        m_axi_matrix_c_0_AWSIZE => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWSIZE,
        m_axi_matrix_c_0_AWBURST => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWBURST,
        m_axi_matrix_c_0_AWLOCK => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWLOCK,
        m_axi_matrix_c_0_AWCACHE => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWCACHE,
        m_axi_matrix_c_0_AWPROT => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWPROT,
        m_axi_matrix_c_0_AWQOS => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWQOS,
        m_axi_matrix_c_0_AWREGION => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWREGION,
        m_axi_matrix_c_0_AWUSER => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWUSER,
        m_axi_matrix_c_0_WVALID => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_WVALID,
        m_axi_matrix_c_0_WREADY => m_axi_matrix_c_0_WREADY,
        m_axi_matrix_c_0_WDATA => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_WDATA,
        m_axi_matrix_c_0_WSTRB => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_WSTRB,
        m_axi_matrix_c_0_WLAST => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_WLAST,
        m_axi_matrix_c_0_WID => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_WID,
        m_axi_matrix_c_0_WUSER => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_WUSER,
        m_axi_matrix_c_0_ARVALID => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARVALID,
        m_axi_matrix_c_0_ARREADY => ap_const_logic_0,
        m_axi_matrix_c_0_ARADDR => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARADDR,
        m_axi_matrix_c_0_ARID => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARID,
        m_axi_matrix_c_0_ARLEN => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARLEN,
        m_axi_matrix_c_0_ARSIZE => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARSIZE,
        m_axi_matrix_c_0_ARBURST => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARBURST,
        m_axi_matrix_c_0_ARLOCK => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARLOCK,
        m_axi_matrix_c_0_ARCACHE => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARCACHE,
        m_axi_matrix_c_0_ARPROT => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARPROT,
        m_axi_matrix_c_0_ARQOS => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARQOS,
        m_axi_matrix_c_0_ARREGION => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARREGION,
        m_axi_matrix_c_0_ARUSER => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_ARUSER,
        m_axi_matrix_c_0_RVALID => ap_const_logic_0,
        m_axi_matrix_c_0_RREADY => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_RREADY,
        m_axi_matrix_c_0_RDATA => ap_const_lv32_0,
        m_axi_matrix_c_0_RLAST => ap_const_logic_0,
        m_axi_matrix_c_0_RID => ap_const_lv1_0,
        m_axi_matrix_c_0_RFIFONUM => ap_const_lv12_0,
        m_axi_matrix_c_0_RUSER => ap_const_lv1_0,
        m_axi_matrix_c_0_RRESP => ap_const_lv2_0,
        m_axi_matrix_c_0_BVALID => m_axi_matrix_c_0_BVALID,
        m_axi_matrix_c_0_BREADY => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_BREADY,
        m_axi_matrix_c_0_BRESP => m_axi_matrix_c_0_BRESP,
        m_axi_matrix_c_0_BID => m_axi_matrix_c_0_BID,
        m_axi_matrix_c_0_BUSER => m_axi_matrix_c_0_BUSER,
        matrix_out => matrix_out,
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        size_ap_vld => size_ap_vld,
        matrix_in_1_ap_vld => matrix_in_1_ap_vld,
        matrix_in_2_ap_vld => matrix_in_2_ap_vld,
        ap_start => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_start,
        matrix_out_ap_vld => matrix_out_ap_vld,
        ap_done => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_done,
        ap_ready => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_ready,
        ap_idle => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_idle,
        ap_continue => dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_continue);





    loop_dataflow_input_count_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                loop_dataflow_input_count <= ap_const_lv28_0;
            else
                if ((not((mul = ap_input_count_plus_step)) and (ap_start = ap_const_logic_1) and (dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_ready = ap_const_logic_1))) then 
                    loop_dataflow_input_count <= ap_input_count_plus_step;
                elsif (((ap_start = ap_const_logic_1) and (dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_ready = ap_const_logic_1) and (mul = ap_input_count_plus_step))) then 
                    loop_dataflow_input_count <= ap_const_lv28_0;
                end if; 
            end if;
        end if;
    end process;


    loop_dataflow_output_count_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                loop_dataflow_output_count <= ap_const_lv28_0;
            else
                if ((not((mul = ap_output_count_plus_step)) and (dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_continue = ap_const_logic_1) and (dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_done = ap_const_logic_1))) then 
                    loop_dataflow_output_count <= ap_output_count_plus_step;
                elsif (((dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_continue = ap_const_logic_1) and (dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_done = ap_const_logic_1) and (mul = ap_output_count_plus_step))) then 
                    loop_dataflow_output_count <= ap_const_lv28_0;
                end if; 
            end if;
        end if;
    end process;


    ap_done_assign_proc : process(mul, dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_done, ap_output_count_plus_step)
    begin
        if (((dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_done = ap_const_logic_1) and (mul = ap_output_count_plus_step))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_idle, ap_start, loop_dataflow_output_count)
    begin
        if (((loop_dataflow_output_count = ap_const_lv28_0) and (ap_start = ap_const_logic_0) and (dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_idle = ap_const_logic_1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_input_count_plus_step <= std_logic_vector(unsigned(loop_dataflow_input_count) + unsigned(ap_const_lv28_1));
    ap_output_count_plus_step <= std_logic_vector(unsigned(loop_dataflow_output_count) + unsigned(ap_const_lv28_1));

    ap_ready_assign_proc : process(mul, dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_ready, ap_start, ap_input_count_plus_step)
    begin
        if (((ap_start = ap_const_logic_1) and (dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_ready = ap_const_logic_1) and (mul = ap_input_count_plus_step))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_continue_assign_proc : process(mul, ap_continue, ap_output_count_plus_step)
    begin
        if ((not((mul = ap_output_count_plus_step)) or (ap_continue = ap_const_logic_1))) then 
            dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_continue <= ap_const_logic_1;
        else 
            dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_continue <= ap_const_logic_0;
        end if; 
    end process;

    dataflow_in_loop_VITIS_LOOP_24_1_1_U0_ap_start <= ap_start;
    m_axi_matrix_a_0_ARADDR <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARADDR;
    m_axi_matrix_a_0_ARBURST <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARBURST;
    m_axi_matrix_a_0_ARCACHE <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARCACHE;
    m_axi_matrix_a_0_ARID <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARID;
    m_axi_matrix_a_0_ARLEN <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARLEN;
    m_axi_matrix_a_0_ARLOCK <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARLOCK;
    m_axi_matrix_a_0_ARPROT <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARPROT;
    m_axi_matrix_a_0_ARQOS <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARQOS;
    m_axi_matrix_a_0_ARREGION <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARREGION;
    m_axi_matrix_a_0_ARSIZE <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARSIZE;
    m_axi_matrix_a_0_ARUSER <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARUSER;
    m_axi_matrix_a_0_ARVALID <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_ARVALID;
    m_axi_matrix_a_0_AWADDR <= ap_const_lv64_0;
    m_axi_matrix_a_0_AWBURST <= ap_const_lv2_0;
    m_axi_matrix_a_0_AWCACHE <= ap_const_lv4_0;
    m_axi_matrix_a_0_AWID <= ap_const_lv1_0;
    m_axi_matrix_a_0_AWLEN <= ap_const_lv32_0;
    m_axi_matrix_a_0_AWLOCK <= ap_const_lv2_0;
    m_axi_matrix_a_0_AWPROT <= ap_const_lv3_0;
    m_axi_matrix_a_0_AWQOS <= ap_const_lv4_0;
    m_axi_matrix_a_0_AWREGION <= ap_const_lv4_0;
    m_axi_matrix_a_0_AWSIZE <= ap_const_lv3_0;
    m_axi_matrix_a_0_AWUSER <= ap_const_lv1_0;
    m_axi_matrix_a_0_AWVALID <= ap_const_logic_0;
    m_axi_matrix_a_0_BREADY <= ap_const_logic_0;
    m_axi_matrix_a_0_RREADY <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_a_0_RREADY;
    m_axi_matrix_a_0_WDATA <= ap_const_lv16_0;
    m_axi_matrix_a_0_WID <= ap_const_lv1_0;
    m_axi_matrix_a_0_WLAST <= ap_const_logic_0;
    m_axi_matrix_a_0_WSTRB <= ap_const_lv2_0;
    m_axi_matrix_a_0_WUSER <= ap_const_lv1_0;
    m_axi_matrix_a_0_WVALID <= ap_const_logic_0;
    m_axi_matrix_b_0_ARADDR <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARADDR;
    m_axi_matrix_b_0_ARBURST <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARBURST;
    m_axi_matrix_b_0_ARCACHE <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARCACHE;
    m_axi_matrix_b_0_ARID <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARID;
    m_axi_matrix_b_0_ARLEN <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARLEN;
    m_axi_matrix_b_0_ARLOCK <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARLOCK;
    m_axi_matrix_b_0_ARPROT <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARPROT;
    m_axi_matrix_b_0_ARQOS <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARQOS;
    m_axi_matrix_b_0_ARREGION <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARREGION;
    m_axi_matrix_b_0_ARSIZE <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARSIZE;
    m_axi_matrix_b_0_ARUSER <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARUSER;
    m_axi_matrix_b_0_ARVALID <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_ARVALID;
    m_axi_matrix_b_0_AWADDR <= ap_const_lv64_0;
    m_axi_matrix_b_0_AWBURST <= ap_const_lv2_0;
    m_axi_matrix_b_0_AWCACHE <= ap_const_lv4_0;
    m_axi_matrix_b_0_AWID <= ap_const_lv1_0;
    m_axi_matrix_b_0_AWLEN <= ap_const_lv32_0;
    m_axi_matrix_b_0_AWLOCK <= ap_const_lv2_0;
    m_axi_matrix_b_0_AWPROT <= ap_const_lv3_0;
    m_axi_matrix_b_0_AWQOS <= ap_const_lv4_0;
    m_axi_matrix_b_0_AWREGION <= ap_const_lv4_0;
    m_axi_matrix_b_0_AWSIZE <= ap_const_lv3_0;
    m_axi_matrix_b_0_AWUSER <= ap_const_lv1_0;
    m_axi_matrix_b_0_AWVALID <= ap_const_logic_0;
    m_axi_matrix_b_0_BREADY <= ap_const_logic_0;
    m_axi_matrix_b_0_RREADY <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_b_0_RREADY;
    m_axi_matrix_b_0_WDATA <= ap_const_lv16_0;
    m_axi_matrix_b_0_WID <= ap_const_lv1_0;
    m_axi_matrix_b_0_WLAST <= ap_const_logic_0;
    m_axi_matrix_b_0_WSTRB <= ap_const_lv2_0;
    m_axi_matrix_b_0_WUSER <= ap_const_lv1_0;
    m_axi_matrix_b_0_WVALID <= ap_const_logic_0;
    m_axi_matrix_c_0_ARADDR <= ap_const_lv64_0;
    m_axi_matrix_c_0_ARBURST <= ap_const_lv2_0;
    m_axi_matrix_c_0_ARCACHE <= ap_const_lv4_0;
    m_axi_matrix_c_0_ARID <= ap_const_lv1_0;
    m_axi_matrix_c_0_ARLEN <= ap_const_lv32_0;
    m_axi_matrix_c_0_ARLOCK <= ap_const_lv2_0;
    m_axi_matrix_c_0_ARPROT <= ap_const_lv3_0;
    m_axi_matrix_c_0_ARQOS <= ap_const_lv4_0;
    m_axi_matrix_c_0_ARREGION <= ap_const_lv4_0;
    m_axi_matrix_c_0_ARSIZE <= ap_const_lv3_0;
    m_axi_matrix_c_0_ARUSER <= ap_const_lv1_0;
    m_axi_matrix_c_0_ARVALID <= ap_const_logic_0;
    m_axi_matrix_c_0_AWADDR <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWADDR;
    m_axi_matrix_c_0_AWBURST <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWBURST;
    m_axi_matrix_c_0_AWCACHE <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWCACHE;
    m_axi_matrix_c_0_AWID <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWID;
    m_axi_matrix_c_0_AWLEN <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWLEN;
    m_axi_matrix_c_0_AWLOCK <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWLOCK;
    m_axi_matrix_c_0_AWPROT <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWPROT;
    m_axi_matrix_c_0_AWQOS <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWQOS;
    m_axi_matrix_c_0_AWREGION <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWREGION;
    m_axi_matrix_c_0_AWSIZE <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWSIZE;
    m_axi_matrix_c_0_AWUSER <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWUSER;
    m_axi_matrix_c_0_AWVALID <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_AWVALID;
    m_axi_matrix_c_0_BREADY <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_BREADY;
    m_axi_matrix_c_0_RREADY <= ap_const_logic_0;
    m_axi_matrix_c_0_WDATA <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_WDATA;
    m_axi_matrix_c_0_WID <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_WID;
    m_axi_matrix_c_0_WLAST <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_WLAST;
    m_axi_matrix_c_0_WSTRB <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_WSTRB;
    m_axi_matrix_c_0_WUSER <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_WUSER;
    m_axi_matrix_c_0_WVALID <= dataflow_in_loop_VITIS_LOOP_24_1_1_U0_m_axi_matrix_c_0_WVALID;
end behav;
